import re

with open('tools/eligibility-checker.html', 'r', encoding='utf-8') as f:
    content = f.read()

extra_seo_content = """
        <div data-lang-show="en" class="mt-4">
          <h3>Why Use Our Sarkari Yojana Eligibility Checker? (2026 Edition)</h3>
          <p>Navigating through hundreds of <strong>Government Schemes (Sarkari Yojana)</strong> can be overwhelming. The Government of India and State Governments launch numerous welfare programs every year for farmers, women, students, and marginalized communities. Our free <strong>Sarkari Scheme Eligibility Checker 2026</strong> acts as your personal scheme finder.</p>
          <p>By using this tool, you avoid the hassle of reading long official PDFs. It instantly matches your age, income, and category with the exact <strong>PM Modi Schemes</strong> and state subsidies you qualify for. From <strong>PM Awas Yojana (PMAY)</strong> housing subsidies to <strong>PM Kisan Samman Nidhi</strong>, and from <strong>Ayushman Bharat</strong> health insurance to <strong>Post Matric Scholarships</strong> – get a customized list with a match score.</p>
          
          <h3>Frequently Asked Questions (FAQs)</h3>
          <div class="faq-container">
            <h4>1. Is this Eligibility Checker completely free to use?</h4>
            <p>Yes, the <strong>SarkariSewaIndia Eligibility Engine</strong> is 100% free. We do not ask for any hidden fees, OTPs, or Aadhar numbers to check your eligibility.</p>
            
            <h4>2. How accurate is the Match Score?</h4>
            <p>The Match Score (0-100%) is generated by analyzing your inputs against the official guidelines of over 35 major government schemes in India. While it is highly accurate based on the data you provide, final approval is always subject to physical document verification by government officials.</p>
            
            <h4>3. Can I apply for the schemes directly from here?</h4>
            <p>Once you see your eligible schemes, we provide a direct <strong>"Apply Online"</strong> link that takes you to the official government portal (e.g., pmkisan.gov.in, pmjay.gov.in) to complete your application safely.</p>

            <h4>4. Do you store my personal information?</h4>
            <p>No. Your privacy is our priority. All eligibility calculations happen instantly on your device (in your browser). We do not save your income, caste, or age data on our servers.</p>
            
            <h4>5. What are the top schemes covered in 2026?</h4>
            <p>Currently, the engine checks eligibility for highly searched schemes including PM Surya Ghar Muft Bijli Yojana, PM Vishwakarma, Lakhpati Didi Yojana, PM Svanidhi, and State-specific schemes like Ladli Behna, Maiya Samman Yojana, and Subhadra Yojana.</p>
          </div>
        </div>
        
        <div data-lang-show="hi" class="mt-4">
          <h3>सरकारी योजना पात्रता खोज इंजन का उपयोग क्यों करें? (2026)</h3>
          <p>भारत सरकार और राज्य सरकारों द्वारा हर साल सैकड़ों <strong>सरकारी योजनाएं (Sarkari Yojana)</strong> शुरू की जाती हैं। लेकिन आम नागरिकों को यह पता नहीं चल पाता कि वे किन योजनाओं का लाभ ले सकते हैं। हमारा <strong>मुफ़्त सरकारी योजना चेक टूल</strong> आपकी उम्र, आय, और व्यवसाय के आधार पर आपको 1 मिनट में बता देता है कि आप किन <strong>पीएम मोदी योजनाओं (PM Modi Yojana)</strong> के लिए पात्र हैं।</p>
          <p>चाहे वह <strong>पीएम आवास योजना</strong> हो, <strong>आयुष्मान भारत कार्ड</strong>, <strong>पीएम किसान सम्मान निधि</strong> या महिलाओं के लिए <strong>लखपति दीदी योजना</strong>, आपको हर योजना की पूरी जानकारी, दस्तावेज़ सूची और डायरेक्ट अप्लाई लिंक यहाँ मिलेंगे।</p>
          
          <h3>अक्सर पूछे जाने वाले प्रश्न (FAQs)</h3>
          <div class="faq-container">
            <h4>1. क्या यह पात्रता चेक टूल मुफ़्त है?</h4>
            <p>हाँ, यह टूल 100% मुफ़्त है। हम पात्रता चेक करने के लिए कोई पैसे या आधार/पैन नंबर नहीं मांगते हैं।</p>
            
            <h4>2. यह टूल किन-किन योजनाओं की जानकारी देता है?</h4>
            <p>यह टूल 35+ से अधिक प्रमुख योजनाओं जैसे पीएम सूर्य घर मुफ़्त बिजली योजना, पीएम विश्वकर्मा, सुकन्या समृद्धि योजना, और विभिन्न राज्यों की पेंशन एवं छात्रवृत्ति योजनाओं की पात्रता चेक करता है।</p>
            
            <h4>3. क्या मैं यहीं से सरकारी योजना के लिए ऑनलाइन अप्लाई (Apply Online) कर सकता हूँ?</h4>
            <p>हाँ! जब आपकी पात्रता मैच हो जाती है, तो हम आपको सीधे <strong>आधिकारिक सरकारी वेबसाइट</strong> का लिंक प्रदान करते हैं ताकि आप बिना किसी फ्रॉड के सुरक्षित तरीके से आवेदन कर सकें।</p>
          </div>
        </div>
"""

# Inject before '<h3 data-lang-show="en">Related Tools</h3>'
new_content = content.replace('<h3 data-lang-show="en">Related Tools</h3>', extra_seo_content + '\n<h3 data-lang-show="en">Related Tools</h3>')

with open('tools/eligibility-checker.html', 'w', encoding='utf-8') as f:
    f.write(new_content)
