# -*- coding: utf-8 -*-
BATCH_2 = {
    'madhya-pradesh-sir-voter-list': {
        'state_en': 'Madhya Pradesh',
        'state_hi': 'मध्य प्रदेश',
        'slug': 'madhya-pradesh-sir-voter-list',
        'title': 'Madhya Pradesh Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Madhya Pradesh Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceomadhyapradesh.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Madhya Pradesh',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी मध्य प्रदेश',
        'total_ac': 230,
        'total_districts': 55,
        'districts': [
            {'name': 'Bhopal', 'ac': 'Bhopal Uttar, Bhopal Dakshin-Paschim, Bhopal Madhya, Govindpura, Huzur, Berasia, Narela'},
            {'name': 'Indore', 'ac': 'Indore-1, Indore-2, Indore-3, Indore-4, Indore-5, Rau, Sanwer, Depalpur, Mhow'},
            {'name': 'Gwalior', 'ac': 'Gwalior, Gwalior Rural, Gwalior East, Gwalior South, Bhitarwar, Dabra'},
            {'name': 'Jabalpur', 'ac': 'Jabalpur East, Jabalpur North, Jabalpur Cantt, Jabalpur West, Panagar, Sihora, Bargi, Patan'},
            {'name': 'Ujjain', 'ac': 'Ujjain North, Ujjain South, Badnagar, Mahidpur, Tarana, Ghatiya, Nagada-Khachrod'},
            {'name': 'Sagar', 'ac': 'Sagar, Bina, Khurai, Surkhi, Deori, Rehli, Naryawali, Banda'},
            {'name': 'Rewa', 'ac': 'Rewa, Gurh, Mangawan, Teonthar, Semariya, Sirmour, Mauganj, Deotalab'},
            {'name': 'Satna', 'ac': 'Satna, Nagod, Maihar, Amarpatan, Rampur-Baghelan, Raigaon, Chitrakoot'},
            {'name': 'Chhindwara', 'ac': 'Chhindwara, Junnardeo, Amarwara, Chourai, Saunsar, Parasia, Pandhurna'},
            {'name': 'Ratlam', 'ac': 'Ratlam City, Ratlam Rural, Sailana, Jaora, Alot'},
            {'name': 'Dewas', 'ac': 'Dewas, Sonkatch, Hatpipliya, Bagli, Khategaon'},
            {'name': 'Morena', 'ac': 'Morena, Dimani, Ambah, Joura, Sabalgarh, Sumawali'},
            {'name': 'Bhind', 'ac': 'Bhind, Ater, Lahar, Mehgaon, Gohad'},
            {'name': 'Shivpuri', 'ac': 'Shivpuri, Pohari, Karera, Kolaras, Pichhore'},
            {'name': 'Guna', 'ac': 'Guna, Bamori, Chachoura, Raghogarh'},
            {'name': 'Vidisha', 'ac': 'Vidisha, Basoda, Kurwai, Sironj, Shamshabad'},
            {'name': 'Sehore', 'ac': 'Sehore, Ashta, Ichhawar, Budhni'},
            {'name': 'Raisen', 'ac': 'Raisen, Sanchi, Silwani, Udaipura, Bhojpur'},
            {'name': 'Khargone (West Nimar)', 'ac': 'Khargone, Kasrawad, Maheshwar, Bhagwanpura, Bhikangaon, Badwah'},
            {'name': 'Khandwa (East Nimar)', 'ac': 'Khandwa, Pandhana, Mandhata, Harsud'},
            {'name': 'Dhar', 'ac': 'Dhar, Dharampuri, Badnawar, Sardarpur, Gandhwani, Kukshi, Manawar'},
            {'name': 'Mandsaur', 'ac': 'Mandsaur, Malhargarh, Suwasra, Garoth'},
            {'name': 'Neemuch', 'ac': 'Neemuch, Manasa, Jawad'},
            {'name': 'Hoshangabad (Narmadapuram)', 'ac': 'Hoshangabad, Itarsi, Seoni-Malwa, Pipariya, Sohagpur'},
            {'name': 'Betul', 'ac': 'Betul, Multai, Amla, Shahpur, Bhainsdehi'},
            {'name': 'Damoh', 'ac': 'Damoh, Hatta, Jabera, Pathariya'},
            {'name': 'Chhatarpur', 'ac': 'Chhatarpur, Maharajpur, Chandla, Rajnagar, Bijawar, Malhara'},
            {'name': 'Tikamgarh', 'ac': 'Tikamgarh, Jatara, Niwari, Prithvipur'},
            {'name': 'Shahdol', 'ac': 'Shahdol, Jaisinghnagar, Jaitpur, Beohari'},
            {'name': 'Katni', 'ac': 'Katni, Murwara, Bahoriband, Barwara, Vijayraghavgarh'},
            {'name': 'Singrauli', 'ac': 'Singrauli, Deosar, Chitrangi'},
            {'name': 'Sidhi', 'ac': 'Sidhi, Sihawal, Churhat, Dhauhani'},
            {'name': 'Balaghat', 'ac': 'Balaghat, Waraseoni, Katangi, Baihar, Lanji, Paraswada'},
            {'name': 'Seoni', 'ac': 'Seoni, Barghat, Keolari, Lakhnadon'},
            {'name': 'Mandla', 'ac': 'Mandla, Bichhiya, Niwas'},
            {'name': 'Dindori', 'ac': 'Dindori, Shahpura'},
            {'name': 'Narsinghpur', 'ac': 'Narsinghpur, Gotegaon, Tendukheda, Gadarwara'},
            {'name': 'Harda', 'ac': 'Harda, Timarni'},
            {'name': 'Rajgarh', 'ac': 'Rajgarh, Biaora, Narsinghgarh, Sarangpur, Khilchipur'},
            {'name': 'Shajapur', 'ac': 'Shajapur, Shujalpur, Kalapipal'},
            {'name': 'Agar Malwa', 'ac': 'Agar, Susner'},
            {'name': 'Barwani', 'ac': 'Barwani, Sendhwa, Rajpur, Pansemal'},
            {'name': 'Alirajpur', 'ac': 'Alirajpur, Jobat'},
            {'name': 'Jhabua', 'ac': 'Jhabua, Thandla, Petlawad'},
            {'name': 'Burhanpur', 'ac': 'Burhanpur, Nepanagar'},
            {'name': 'Anuppur', 'ac': 'Anuppur, Kotma, Pushprajgarh'},
            {'name': 'Umaria', 'ac': 'Bandhavgarh, Manpur'},
            {'name': 'Panna', 'ac': 'Panna, Gunnaor, Pawai'},
            {'name': 'Sheopur', 'ac': 'Sheopur, Vijaypur'},
            {'name': 'Datia', 'ac': 'Datia, Sewda, Bhander'},
            {'name': 'Ashoknagar', 'ac': 'Ashoknagar, Chanderi, Mungaoli'},
            {'name': 'Niwari', 'ac': 'Niwari, Prithvipur'},
            {'name': 'Mauganj', 'ac': 'Mauganj, Hanumana, Deotalab'},
            {'name': 'Maihar', 'ac': 'Maihar, Amarpatan'},
            {'name': 'Pandhurna', 'ac': 'Pandhurna, Saunsar'}
        ]
    },
    'maharashtra-sir-voter-list': {
        'state_en': 'Maharashtra',
        'state_hi': 'महाराष्ट्र',
        'slug': 'maharashtra-sir-voter-list',
        'title': 'Maharashtra Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Maharashtra Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceoelection.maharashtra.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Maharashtra',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी महाराष्ट्र',
        'total_ac': 288,
        'total_districts': 36,
        'districts': [
            {'name': 'Mumbai City', 'ac': 'Colaba, Mumbadevi, Malabar Hill, Byculla, Shivadi, Sion Koliwada, Wadala, Dharavi, Mahim, Worli'},
            {'name': 'Mumbai Suburban', 'ac': 'Bandra West, Bandra East, Andheri West, Andheri East, Versova, Vile Parle, Borivali, Dahisar, Magathane, Kandivali, Charkop, Malad, Dindoshi, Goregaon, Ghatkopar, Vikhroli, Bhandup, Mulund, Chembur, Kurla, Chandivali, Anushakti Nagar, Mankhurd Shivaji Nagar'},
            {'name': 'Pune', 'ac': 'Kasba Peth, Shivajinagar, Kothrud, Pune Cantonment, Parvati, Vadgaon Sheri, Hadapsar, Baramati, Shirur, Daund, Indapur, Purandar, Bhor, Maval, Chinchwad, Pimpri, Bhosari, Khed Alandi, Ambegaon, Junnar'},
            {'name': 'Nagpur', 'ac': 'Nagpur South West, Nagpur South, Nagpur East, Nagpur Central, Nagpur West, Nagpur North, Katol, Savner, Hingna, Umred, Kamthi, Ramtek'},
            {'name': 'Thane', 'ac': 'Thane City, Kopri-Pachpakhadi, Ovala-Majiwada, Kalyan West, Kalyan East, Kalyan Rural, Dombivli, Mumbra-Kalwa, Mira Bhayandar, Ulhasnagar, Ambernath, Bhiwandi West, Bhiwandi East, Bhiwandi Rural, Shahapur, Murbad'},
            {'name': 'Nashik', 'ac': 'Nashik Central, Nashik West, Nashik East, Deolali, Sinnar, Niphad, Dindori, Yeola, Nandgaon, Malegaon Central, Malegaon Outer, Baglan, Kalwan, Chandwad, Igatpuri'},
            {'name': 'Chhatrapati Sambhajinagar (Aurangabad)', 'ac': 'Aurangabad Central, Aurangabad West, Aurangabad East, Paithan, Gangapur, Vaijapur, Kannad, Sillod, Phulambri'},
            {'name': 'Solapur', 'ac': 'Solapur City North, Solapur City Central, Solapur South, Barshi, Mohol, Madha, Karmala, Pandharpur, Sangole, Malshiras, Akkalkot'},
            {'name': 'Kolhapur', 'ac': 'Kolhapur South, Kolhapur North, Karvir, Shahuwadi, Radhanagari, Kagal, Hatkanangle, Ichalkaranji, Shirol, Chandgad, Radhanagari'},
            {'name': 'Amravati', 'ac': 'Amravati, Badnera, Achalpur, Melghat, Morshi, Teosa, Daryapur, Dhamangaon Railway'},
            {'name': 'Nanded', 'ac': 'Nanded North, Nanded South, Deglur, Mukhed, Bhokar, Loha, Hadgaon, Kinwat, Naigaon'},
            {'name': 'Sangli', 'ac': 'Sangli, Miraj, Islampur, Shirala, Palus-Kadegaon, Khanapur, Tasgaon-Kavathe Mahankal, Jat'},
            {'name': 'Jalgaon', 'ac': 'Jalgaon City, Jalgaon Rural, Bhusawal, Chalisgaon, Jamner, Erandol, Pachora, Raver, Chopda, Amalner, Muktainagar'},
            {'name': 'Akola', 'ac': 'Akola West, Akola East, Balapur, Murtizapur, Akot'},
            {'name': 'Latur', 'ac': 'Latur City, Latur Rural, Udgir, Nilanga, Ausa, Ahmadpur'},
            {'name': 'Dhule', 'ac': 'Dhule City, Dhule Rural, Sindkheda, Shirpur, Sakri'},
            {'name': 'Ahmednagar (Ahilyanagar)', 'ac': 'Ahmednagar City, Rahuri, Shirdi, Kopargaon, Shrirampur, Nevasa, Shevgaon, Parner, Sangamner, Akole, Karjat Jamkhed, Shrigonda'},
            {'name': 'Satara', 'ac': 'Satara, Karad North, Karad South, Koregaon, Wai, Phaltan, Man, Patan'},
            {'name': 'Raigad', 'ac': 'Alibag, Panvel, Karjat, Uran, Pen, Mahad, Shrivardhan'},
            {'name': 'Palghar', 'ac': 'Vasai, Nalasopara, Boisar, Palghar, Dahanu, Vikramgad'},
            {'name': 'Ratnagiri', 'ac': 'Ratnagiri, Chiplun, Guhagar, Rajapur, Dapoli'},
            {'name': 'Sindhudurg', 'ac': 'Kankavli, Kudal, Sawantwadi'},
            {'name': 'Jalna', 'ac': 'Jalna, Badnapur, Bhokardan, Partur, Ghansawangi'},
            {'name': 'Beed', 'ac': 'Beed, Georai, Majalgaon, Ashti, Kaij, Parli'},
            {'name': 'Parbhani', 'ac': 'Parbhani, Jintur, Gangakhed, Pathri'},
            {'name': 'Hingoli', 'ac': 'Hingoli, Basmath, Kalamnuri'},
            {'name': 'Osmanabad (Dharashiv)', 'ac': 'Osmanabad, Tuljapur, Umarga, Paranda'},
            {'name': 'Yavatmal', 'ac': 'Yavatmal, Arni, Pusad, Umarkhed, Digras, Wani, Ralegaon'},
            {'name': 'Buldhana', 'ac': 'Buldhana, Chikhli, Sindkhed Raja, Mehkar, Khamgaon, Jalgaon Jamod, Malkapur'},
            {'name': 'Washim', 'ac': 'Washim, Karanja, Risod'},
            {'name': 'Wardha', 'ac': 'Wardha, Deoli, Arvi, Hinganghat'},
            {'name': 'Chandrapur', 'ac': 'Chandrapur, Ballarpur, Warora, Bramhapuri, Chimur, Rajura'},
            {'name': 'Gadchiroli', 'ac': 'Gadchiroli, Armori, Aheri'},
            {'name': 'Gondia', 'ac': 'Gondia, Tirora, Amgaon, Arjuni Morgaon'},
            {'name': 'Bhandara', 'ac': 'Bhandara, Sakoli, Tumsar'},
            {'name': 'Nandurbar', 'ac': 'Nandurbar, Shahada, Nawapur, Akkalkuwa'}
        ]
    },
    'delhi-sir-voter-list': {
        'state_en': 'Delhi (NCT)',
        'state_hi': 'दिल्ली (NCT)',
        'slug': 'delhi-sir-voter-list',
        'title': 'Delhi Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Delhi Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceodelhi.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Delhi',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी दिल्ली',
        'total_ac': 70,
        'total_districts': 11,
        'districts': [
            {'name': 'New Delhi', 'ac': 'New Delhi, Delhi Cantt, Greater Kailash, Kasturba Nagar, Malviya Nagar, R K Puram'},
            {'name': 'Central Delhi', 'ac': 'Chandni Chowk, Matia Mahal, Ballimaran, Karol Bagh, Patel Nagar, Sadar Bazar'},
            {'name': 'North Delhi', 'ac': 'Burari, Timarpur, Adarsh Nagar, Badli, Rithala, Bawana, Narela'},
            {'name': 'South Delhi', 'ac': 'Mehrauli, Chhatarpur, Deoli, Ambedkar Nagar, Sangam Vihar, Tughlakabad, Badarpur'},
            {'name': 'East Delhi', 'ac': 'Gandhi Nagar, Krishna Nagar, Vishwas Nagar, Shahdara, Laxmi Nagar, Patparganj, Kondli, Trilokpuri'},
            {'name': 'West Delhi', 'ac': 'Janakpuri, Tilak Nagar, Hari Nagar, Rajouri Garden, Madipur, Uttam Nagar, Vikaspuri'},
            {'name': 'North West Delhi', 'ac': 'Rohini, Mangolpuri, Sultanpur Majra, Nangloi Jat, Mundka, Kirari, Shakur Basti, Tri Nagar, Wazirpur, Model Town'},
            {'name': 'South West Delhi', 'ac': 'Dwarka, Matiala, Najafgarh, Bijwasan, Palam'},
            {'name': 'North East Delhi', 'ac': 'Seelampur, Gonda, Ghonda, Babarpur, Gokulpur, Mustafabad, Karawal Nagar, Rohtas Nagar'},
            {'name': 'South East Delhi', 'ac': 'Okhla, Jangpura, Kalkaji, Sarita Vihar'},
            {'name': 'Shahdara', 'ac': 'Shahdara, Seemapuri, Rohtas Nagar, Babarpur'}
        ]
    }
}
print('Batch 2 data ready (MP, Maharashtra, Delhi)...')
