# -*- coding: utf-8 -*-
BATCH_5 = {
    'karnataka-sir-voter-list': {
        'state_en': 'Karnataka',
        'state_hi': 'कर्नाटक',
        'slug': 'karnataka-sir-voter-list',
        'title': 'Karnataka Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Karnataka Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceokarnataka.kar.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Karnataka',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी कर्नाटक',
        'total_ac': 224,
        'total_districts': 31,
        'districts': [
            {'name': 'Bengaluru Urban', 'ac': 'Malleshwaram, Gandhinagar, Rajajinagar, Chamrajpet, Chickpet, Shantinagar, Shivajinagar, BTM Layout, Jayanagar, Padmanabhanagar, Basavanagudi, Bommanahalli, Mahadevapura, KR Puram, CV Raman Nagar, Hebbal, Pulakeshinagar, Sarvagnanagar, Byatarayanapura, Yeshwantpur, Dasarahalli, Bangalore South, Anekal'},
            {'name': 'Bengaluru Rural', 'ac': 'Hosakote, Devanahalli, Doddaballapur, Nelamangala'},
            {'name': 'Mysuru (Mysore)', 'ac': 'Krishnaraja, Chamaraja, Narasimharaja, Chamundeshwari, Varuna, T. Narasipura, Hunsur, Piriyapatna, Heggadadevankote, K.R. Nagar'},
            {'name': 'Belagavi (Belgaum)', 'ac': 'Belgaum Uttar, Belgaum Dakshin, Belgaum Rural, Gokak, Arabhavi, Hukkeri, Chikkodi-Sadalga, Athani, Kagwad, Kudachi, Raybag, Bailhongal, Saundatti Yellamma, Ramdurg, Khanapur, Kittur'},
            {'name': 'Dharwad (Hubballi-Dharwad)', 'ac': 'Hubli-Dharwad Central, Hubli-Dharwad East, Hubli-Dharwad West, Dharwad, Navalgund, Kundgol, Kalghatgi'},
            {'name': 'Dakshina Kannada (Mangaluru)', 'ac': 'Mangalore City South, Mangalore City North, Mangalore, Bantwal, Belthangady, Puttur, Sullia, Moodabidri'},
            {'name': 'Kalaburagi (Gulbarga)', 'ac': 'Gulbarga Uttar, Gulbarga Dakshin, Gulbarga Rural, Afzalpur, Jevargi, Sedam, Chincholi, Aland, Chittapur'},
            {'name': 'Tumakuru (Tumkur)', 'ac': 'Tumkur City, Tumkur Rural, Tiptur, Chiknayakanhalli, Gubbi, Sira, Pavagada, Madhugiri, Koratagere, Turuvekere'},
            {'name': 'Ballari (Bellary)', 'ac': 'Bellary City, Bellary Rural, Kampli, Siruguppa, Sandur'},
            {'name': 'Vijayapura (Bijapur)', 'ac': 'Bijapur City, Babaleshwar, Basavana Bagevadi, Muddebihal, Devar Hippargi, Sindgi, Nagathan, Indi'},
            {'name': 'Shivamogga (Shimoga)', 'ac': 'Shimoga, Shimoga Rural, Bhadravati, Thirthahalli, Sagar, Shikaripura, Sorab'},
            {'name': 'Davanagere', 'ac': 'Davanagere North, Davanagere South, Mayakonda, Channagiri, Honnali, Harihar, Jagalur'},
            {'name': 'Udupi', 'ac': 'Udupi, Kaup, Kundapura, Byndoor, Karkala'},
            {'name': 'Hassan', 'ac': 'Hassan, Holenarasipur, Arkalgud, Sakleshpur, Belur, Arsikere, Channarayapatna'},
            {'name': 'Mandya', 'ac': 'Mandya, Maddur, Malavalli, Srirangapatna, Nagamangala, Krishnarajpet, Melukote'},
            {'name': 'Chikkamagaluru', 'ac': 'Chikmagalur, Kadur, Tarikere, Mudigere, Sringeri'},
            {'name': 'Uttara Kannada (Karwar)', 'ac': 'Karwar, Kumta, Bhatkal, Sirsi, Yellapur, Haliyal'},
            {'name': 'Raichur', 'ac': 'Raichur, Raichur Rural, Manvi, Sindhanur, Maski, Lingsugur, Devadurga'},
            {'name': 'Koppal', 'ac': 'Koppal, Gangawati, Kushtagi, Yelburga, Kanakagiri'},
            {'name': 'Bagalkote', 'ac': 'Bagalkot, Badami, Jamkhandi, Mudhol, Bilgi, Hungund, Terdal'},
            {'name': 'Gadag', 'ac': 'Gadag, Ron, Shirahatti, Nargund'},
            {'name': 'Haveri', 'ac': 'Haveri, Byadgi, Ranibennur, Hirekerur, Shiggaon, Hangal'},
            {'name': 'Bidar', 'ac': 'Bidar, Bidar South, Bhalki, Humnabad, Aurad, Basavakalyan'},
            {'name': 'Yadgir', 'ac': 'Yadgir, Shahapur, Surpur, Gurmitkal'},
            {'name': 'Chitradurga', 'ac': 'Chitradurga, Challakere, Hiriyur, Hosadurga, Holalkere, Molakalmuru'},
            {'name': 'Kolar', 'ac': 'Kolar, Kolar Gold Fields (KGF), Malur, Bangarapet, Srinivaspur'},
            {'name': 'Chikkaballapura', 'ac': 'Chikkaballapur, Gauribidanur, Bagepalli, Shidlaghatta, Chintamani'},
            {'name': 'Ramanagara', 'ac': 'Ramanagaram, Kanakapura, Channapatna, Magadi'},
            {'name': 'Chamarajanagar', 'ac': 'Chamarajanagar, Gundlupet, Kollegal, Hanur'},
            {'name': 'Kodagu (Madikeri)', 'ac': 'Madikeri, Virajpet'},
            {'name': 'Vijayanagara (Hosapete)', 'ac': 'Vijayanagara, Harapanahalli, Hadagalli, Hagaribommanahalli, Kudligi'}
        ]
    },
    'andhra-pradesh-sir-voter-list': {
        'state_en': 'Andhra Pradesh',
        'state_hi': 'आंध्र प्रदेश',
        'slug': 'andhra-pradesh-sir-voter-list',
        'title': 'Andhra Pradesh Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Andhra Pradesh Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceoandhra.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Andhra Pradesh',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी आंध्र प्रदेश',
        'total_ac': 175,
        'total_districts': 26,
        'districts': [
            {'name': 'Visakhapatnam', 'ac': 'Visakhapatnam East, Visakhapatnam South, Visakhapatnam North, Visakhapatnam West, Bheemili, Gajuwaka, Pendurthi'},
            {'name': 'NTR (Vijayawada)', 'ac': 'Vijayawada Central, Vijayawada East, Vijayawada West, Mylavaram, Nandigama, Jaggayyapeta, Tiruvuru'},
            {'name': 'Guntur', 'ac': 'Guntur East, Guntur West, Ponnur, Tadikonda, Mangalagiri, Tenali, Prathipadu'},
            {'name': 'Tirupati', 'ac': 'Tirupati, Chandragiri, Srikalahasti, Satyavedu, Nagari, Gudur, Sullurpeta, Venkatagiri'},
            {'name': 'Kurnool', 'ac': 'Kurnool, Kodumur, Yemmiganur, Mantralayam, Adoni, Alur, Pattikonda'},
            {'name': 'Kakinada', 'ac': 'Kakinada City, Kakinada Rural, Peddapuram, Pithapuram, Tuni, Prathipadu, Jaggampeta'},
            {'name': 'East Godavari (Rajahmundry)', 'ac': 'Rajahmundry City, Rajahmundry Rural, Anaparthy, Rajanagaram, Kovvur, Nidadavole, Gopalapuram'},
            {'name': 'West Godavari (Bhimavaram)', 'ac': 'Bhimavaram, Narasapuram, Palakollu, Tadepalligudem, Tanuku, Achanta, Undi'},
            {'name': 'Krishna (Machilipatnam)', 'ac': 'Machilipatnam, Gudivada, Pamarru, Penamaluru, Gannavaram, Pedana, Avanigadda'},
            {'name': 'Prakasam (Ongole)', 'ac': 'Ongole, Chirala, Parchur, Addanki, Santhanuthalapadu, Kandukur, Darsi, Markapuram, Giddalur, Yerragondapalem, Kanigiri'},
            {'name': 'Nellore (SPSR Nellore)', 'ac': 'Nellore City, Nellore Rural, Sarvepalli, Kovur, Atmakur, Udayagiri, Kavali'},
            {'name': 'Anantapur', 'ac': 'Anantapur Urban, Guntakal, Tadipatri, Singanamala, Rayadurg, Uravakonda, Kalyandurg'},
            {'name': 'YSR Kadapa', 'ac': 'Kadapa, Kamalapuram, Proddatur, Jammalamadugu, Pulivendula, Mydukur, Badvel'},
            {'name': 'Chittoor', 'ac': 'Chittoor, Nagari, Gangadhara Nellore, Puthalapattu, Palamaner, Kuppam'},
            {'name': 'Srikakulam', 'ac': 'Srikakulam, Amadalavalasa, Narasannapeta, Tekkali, Palasa, Ichchapuram, Pathapatnam, Rajam'},
            {'name': 'Vizianagaram', 'ac': 'Vizianagaram, Cheepurupalli, Gajapathinagaram, Nellimarla, Bobbili, Srungavarapukota, Kurupam, Parvathipuram, Salur'},
            {'name': 'Eluru', 'ac': 'Eluru, Denduluru, Unguturu, Chintalapudi, Polavaram, Kaikalur, Nuzvid'},
            {'name': 'Nandyal', 'ac': 'Nandyal, Allagadda, Banaganapalle, Dhone, Nandikotkur, Srisailam'},
            {'name': 'Sri Sathya Sai (Puttaparthi)', 'ac': 'Puttaparthi, Dharmavaram, Kadiri, Penukonda, Hindupur, Madakasira'},
            {'name': 'Annamayya (Rayachoti)', 'ac': 'Rayachoti, Rajampet, Kodur, Madanapalle, Thamballapalle, Pileru'},
            {'name': 'Bapatla', 'ac': 'Bapatla, Chirala, Parchur, Addanki, Vemuru, Repalle'},
            {'name': 'Palnadu (Narasaraopet)', 'ac': 'Narasaraopet, Sattenapalle, Vinukonda, Gurazala, Macherla, Pedakurapadu, Chilakaluripet'},
            {'name': 'Konaseema (Amalapuram)', 'ac': 'Amalapuram, Razole, Gannavaram, Kothapeta, Mandapeta, Ramachandrapuram, Mummidivaram'},
            {'name': 'Anakapalli', 'ac': 'Anakapalle, Chodavaram, Madugula, Elamanchili, Payakaraopet, Narsipatnam, Pendurthi'},
            {'name': 'Alluri Sitharama Raju (Paderu)', 'ac': 'Paderu, Araku Valley, Rampachodavaram'},
            {'name': 'Parvathipuram Manyam', 'ac': 'Parvathipuram, Kurupam, Salur, Palakonda'}
        ]
    },
    'telangana-sir-voter-list': {
        'state_en': 'Telangana',
        'state_hi': 'तेलंगाना',
        'slug': 'telangana-sir-voter-list',
        'title': 'Telangana Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Telangana Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceotelangana.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Telangana',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी तेलंगाना',
        'total_ac': 119,
        'total_districts': 33,
        'districts': [
            {'name': 'Hyderabad', 'ac': 'Charminar, Chandrayangutta, Yakutpura, Bahadurpura, Malakpet, Goshamahal, Karwan, Nampally, Khairatabad, Jubilee Hills, Sanathnagar, Amberpet, Musheerabad, Secunderabad, Secunderabad Cantt'},
            {'name': 'Medchal-Malkajgiri', 'ac': 'Malkajgiri, Quthbullapur, Kukatpally, Uppal, Medchal'},
            {'name': 'Rangareddy', 'ac': 'L.B. Nagar, Maheshwaram, Rajendranagar, Serilingampally, Chevella, Ibrahimpatnam, Shadnagar'},
            {'name': 'Warangal (Urban & Rural)', 'ac': 'Warangal East, Warangal West, Wardhannapet, Parkal, Narsampet'},
            {'name': 'Karimnagar', 'ac': 'Karimnagar, Choppadandi, Manakondur, Huzurabad'},
            {'name': 'Nizamabad', 'ac': 'Nizamabad Urban, Nizamabad Rural, Bodhan, Armoor, Balkonda'},
            {'name': 'Khammam', 'ac': 'Khammam, Palair, Madhira, Wyra, Sathupalli'},
            {'name': 'Nalgonda', 'ac': 'Nalgonda, Miryalaguda, Devarakonda, Nagarjuna Sagar, Nakrekal, Munugode'},
            {'name': 'Mahabubnagar', 'ac': 'Mahabubnagar, Jadcherla, Devarakadra'},
            {'name': 'Sangareddy', 'ac': 'Sangareddy, Patancheru, Zahirabad, Andole, Narayankhed'},
            {'name': 'Siddipet', 'ac': 'Siddipet, Gajwel, Dubbak, Husnabad'},
            {'name': 'Medak', 'ac': 'Medak, Narsapur'},
            {'name': 'Adilabad', 'ac': 'Adilabad, Boath'},
            {'name': 'Mancherial', 'ac': 'Mancherial, Bellampalli, Chennur'},
            {'name': 'Nirmal', 'ac': 'Nirmal, Mudhole, Khanapur'},
            {'name': 'Kumuram Bheem Asifabad', 'ac': 'Asifabad, Sirpur'},
            {'name': 'Jagtial', 'ac': 'Jagtial, Koratla, Dharmapuri'},
            {'name': 'Peddapalli', 'ac': 'Peddapalli, Ramagundam, Manthani'},
            {'name': 'Rajanna Sircilla', 'ac': 'Sircilla, Vemulawada'},
            {'name': 'Kamareddy', 'ac': 'Kamareddy, Yellareddy, Jukkal'},
            {'name': 'Bhadradri Kothagudem', 'ac': 'Kothagudem, Bhadrachalam, Yellandu, Pinapaka, Aswaraopeta'},
            {'name': 'Mahabubabad', 'ac': 'Mahabubabad, Dornakal'},
            {'name': 'Jangaon', 'ac': 'Jangaon, Station Ghanpur, Palakurthi'},
            {'name': 'Jayashankar Bhupalpally', 'ac': 'Bhupalpalle'},
            {'name': 'Mulugu', 'ac': 'Mulug'},
            {'name': 'Suryapet', 'ac': 'Suryapet, Kodad, Huzurnagar, Tungaturthi'},
            {'name': 'Yadadri Bhuvanagiri', 'ac': 'Bhongir, Alair'},
            {'name': 'Nagarkurnool', 'ac': 'Nagarkurnool, Achampet, Kollapur, Kalwakurthy'},
            {'name': 'Wanaparthy', 'ac': 'Wanaparthy'},
            {'name': 'Jogulamba Gadwal', 'ac': 'Gadwal, Alampur'},
            {'name': 'Narayanpet', 'ac': 'Narayanpet, Makthal'},
            {'name': 'Vikarabad', 'ac': 'Vikarabad, Tandur, Pargi, Kodangal'},
            {'name': 'Hanamkonda', 'ac': 'Hanamkonda, Warangal West'}
        ]
    },
    'tamil-nadu-sir-voter-list': {
        'state_en': 'Tamil Nadu',
        'state_hi': 'तमिलनाडु',
        'slug': 'tamil-nadu-sir-voter-list',
        'title': 'Tamil Nadu Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Tamil Nadu Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://elections.tn.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Tamil Nadu',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी तमिलनाडु',
        'total_ac': 234,
        'total_districts': 38,
        'districts': [
            {'name': 'Chennai', 'ac': 'Dr. Radhakrishnan Nagar, Perambur, Kolathur, Villivakkam, Thiru-Vi-Ka-Nagar, Egmore, Royapuram, Harbour, Chepauk-Thiruvallikeni, Thousand Lights, Anna Nagar, Virugampakkam, Saidapet, Thiyagarayanagar, Mylapore, Velachery'},
            {'name': 'Coimbatore', 'ac': 'Coimbatore North, Coimbatore South, Singanallur, Kavundampalayam, Thondamuthur, Sulur, Kinathukadavu, Pollachi, Valparai, Mettupalayam'},
            {'name': 'Madurai', 'ac': 'Madurai North, Madurai South, Madurai Central, Madurai West, Madurai East, Melur, Sholavandan, Thiruparankundram, Thirumangalam, Usilampatti'},
            {'name': 'Tiruchirappalli (Trichy)', 'ac': 'Tiruchirappalli West, Tiruchirappalli East, Srirangam, Thiruverumbur, Lalgudi, Manachanallur, Musiri, Thuraiyur, Manapparai'},
            {'name': 'Salem', 'ac': 'Salem North, Salem South, Salem West, Omalur, Mettur, Edappadi, Sankari, Yercaud, Veerapandi, Attur, Gangavalli'},
            {'name': 'Tirunelveli', 'ac': 'Tirunelveli, Palayamkottai, Ambasamudram, Nanguneri, Radhapuram'},
            {'name': 'Erode', 'ac': 'Erode East, Erode West, Modakkurichi, Perundurai, Bhavani, Anthiyur, Gobichettipalayam, Bhavanisagar'},
            {'name': 'Tiruppur', 'ac': 'Tiruppur North, Tiruppur South, Avinashi, Palladam, Kangayam, Dharapuram, Udumalaipettai, Madathukulam'},
            {'name': 'Vellore', 'ac': 'Vellore, Anaicut, Kilvaithinankuppam, Gudiyattam, Katpadi'},
            {'name': 'Kanchipuram', 'ac': 'Kanchipuram, Sriperumbudur, Uthiramerur'},
            {'name': 'Chengalpattu', 'ac': 'Chengalpattu, Tambaram, Pallavaram, Sholinganallur, Madurantakam, Cheyyur, Thiruporur'},
            {'name': 'Thiruvallur', 'ac': 'Tiruvallur, Avadi, Poonamallee, Madavaram, Ambattur, Gummidipoondi, Ponneri, Tiruttani'},
            {'name': 'Thanjavur', 'ac': 'Thanjavur, Kumbakonam, Papanasam, Thiruvaiyaru, Orathanadu, Pattukkottai, Peravurani, Thiruvidaimarudur'},
            {'name': 'Dindigul', 'ac': 'Dindigul, Athoor, Nilakkottai, Natham, Oddanchatram, Palani, Vedasandur'},
            {'name': 'Kanyakumari (Nagercoil)', 'ac': 'Nagercoil, Kanyakumari, Colachel, Padmanabhapuram, Vilavancode, Killiyoor'},
            {'name': 'Cuddalore', 'ac': 'Cuddalore, Panruti, Neyveli, Vridhachalam, Tittakudi, Chidambaram, Bhuvanagiri, Kattumannarkoil'},
            {'name': 'Villupuram', 'ac': 'Villupuram, Vikravandi, Tindivanam, Vanur, Mailam, Gingee'},
            {'name': 'Dharmapuri', 'ac': 'Dharmapuri, Pennagaram, Harur, Palacode, Pappireddippatti'},
            {'name': 'Krishnagiri', 'ac': 'Krishnagiri, Hosur, Bargur, Pochampalli, Uthangarai, Thalli'},
            {'name': 'Namakkal', 'ac': 'Namakkal, Rasipuram, Tiruchengode, Paramathi Velur, Senthamangalam, Kumarapalayam'},
            {'name': 'Karur', 'ac': 'Karur, Aravakurichi, Krishnarayapuram, Kulithalai'},
            {'name': 'Pudukkottai', 'ac': 'Pudukkottai, Gandarvakottai, Viralimalai, Thirumayam, Alangudi, Aranthangi'},
            {'name': 'Sivaganga', 'ac': 'Sivaganga, Karaikudi, Tiruppattur, Manamadurai'},
            {'name': 'Ramanathapuram', 'ac': 'Ramanathapuram, Rameswaram, Paramakudi, Tiruvadanai, Mudukulathur'},
            {'name': 'Virudhunagar', 'ac': 'Virudhunagar, Sivakasi, Rajapalayam, Srivilliputhur, Sattur, Aruppukkottai, Tiruchuli'},
            {'name': 'Thoothukudi (Tuticorin)', 'ac': 'Thoothukkudi, Tiruchendur, Srivaikuntam, Ottapidaram, Kovilpatti, Vilathikulam'},
            {'name': 'Tenkasi', 'ac': 'Tenkasi, Kadayanallur, Vasudevanallur, Sankarankovil, Alangulam'},
            {'name': 'Ranipet', 'ac': 'Ranipet, Arcot, Sholinghur, Arakkonam'},
            {'name': 'Tirupattur', 'ac': 'Tirupattur, Vaniyambadi, Ambur, Jolarpet'},
            {'name': 'Kallakurichi', 'ac': 'Kallakurichi, Sankarapuram, Rishivandiyam, Ulundurpet'},
            {'name': 'Mayiladuthurai', 'ac': 'Mayiladuthurai, Sirkazhi, Poompuhar'},
            {'name': 'Nagapattinam', 'ac': 'Nagapattinam, Kilvelur, Vedaranyam'},
            {'name': 'Tiruvarur', 'ac': 'Tiruvarur, Mannargudi, Thiruthuraipoondi, Nannilam'},
            {'name': 'Perambalur', 'ac': 'Perambalur, Kunnam'},
            {'name': 'Ariyalur', 'ac': 'Ariyalur, Jayankondam'},
            {'name': 'Theni', 'ac': 'Theni, Periyakulam, Bodinayakanur, Cumbum'},
            {'name': 'Tiruvannamalai', 'ac': 'Tiruvannamalai, Chengam, Polur, Arani, Cheyyar, Vandavasi, Kalasapakkam, Kilpennathur'},
            {'name': 'Nilgiris (Ooty)', 'ac': 'Udhagamandalam, Coonoor, Gudalur'}
        ]
    },
    'kerala-sir-voter-list': {
        'state_en': 'Kerala',
        'state_hi': 'केरल',
        'slug': 'kerala-sir-voter-list',
        'title': 'Kerala Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Kerala Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceo.kerala.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Kerala',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी केरल',
        'total_ac': 140,
        'total_districts': 14,
        'districts': [
            {'name': 'Thiruvananthapuram', 'ac': 'Thiruvananthapuram, Nemom, Kazhakkoottam, Vattiyoorkavu, Kovalam, Neyyattinkara, Parassala, Kattakkada, Aruvikkara, Nedumangad, Vamanapuram, Attingal, Chirayinkeezhu, Varkala'},
            {'name': 'Ernakulam (Kochi)', 'ac': 'Ernakulam, Kochi, Thrikkakara, Kalamassery, Aluva, Paravur, Vypin, Angamaly, Perumbavoor, Kunnathunad, Muvattupuzha, Kothamangalam, Piravom, Annamanada'},
            {'name': 'Kozhikode (Calicut)', 'ac': 'Kozhikode North, Kozhikode South, Beypore, Elathur, Kunnamangalam, Koduvally, Thiruvambady, Balusseri, Perambra, Quilandy, Vadakara, Kuttiadi, Nadapuram'},
            {'name': 'Thrissur', 'ac': 'Thrissur, Ollur, Guruvayoor, Kunnamkulam, Wadakkanchery, Manalur, Nattika, Kaipamangalam, Irinjalakuda, Puthukkad, Chalakudy, Kodungallur, Chelakkara'},
            {'name': 'Malappuram', 'ac': 'Malappuram, Manjeri, Kondotty, Vallikkunnu, Vengara, Tirurangadi, Tanur, Tirur, Kottakkal, Thavanur, Ponnani, Perinthalmanna, Mankada, Wandoor, Nilambur, Eranad'},
            {'name': 'Palakkad', 'ac': 'Palakkad, Chittur, Nenmara, Alathur, Tarur, Kongad, Mannarkkad, Ottapalam, Shoranur, Pattambi, Thrithala, Malampuzha'},
            {'name': 'Kollam', 'ac': 'Kollam, Eravipuram, Chathannoor, Kundara, Kottarakkara, Pathanapuram, Punalur, Chadayamangalam, Kunnathur, Karunagappally, Chavara'},
            {'name': 'Alappuzha (Alleppey)', 'ac': 'Alappuzha, Ambalappuzha, Cherthala, Aroor, Kuttanad, Haripad, Kayamkulam, Mavelikkara, Chengannur'},
            {'name': 'Kottayam', 'ac': 'Kottayam, Changanassery, Vaikom, Kaduthuruthy, Ettumanoor, Puthuppally, Pala, Poonjar, Kanjirappally'},
            {'name': 'Kannur', 'ac': 'Kannur, Azhikode, Dharmadam, Thalassery, Mattannur, Kuthuparamba, Taliparamba, Irikkur, Payyannur, Kalliasseri, Peravoor'},
            {'name': 'Kasaragod', 'ac': 'Kasaragod, Manjeshwar, Udma, Kanhangad, Trikaripur'},
            {'name': 'Pathanamthitta', 'ac': 'Pathanamthitta, Adoor, Ranni, Aranmula, Thiruvalla, Konni'},
            {'name': 'Idukki', 'ac': 'Idukki, Devikulam, Udumbanchola, Thodupuzha, Peerumade'},
            {'name': 'Wayanad', 'ac': 'Kalpetta, Sulthan Bathery, Mananthavady'}
        ]
    },
    'assam-sir-voter-list': {
        'state_en': 'Assam',
        'state_hi': 'असम',
        'slug': 'assam-sir-voter-list',
        'title': 'Assam Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Assam Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceoassam.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Assam',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी असम',
        'total_ac': 126,
        'total_districts': 35,
        'districts': [
            {'name': 'Kamrup Metropolitan (Guwahati)', 'ac': 'Guwahati East, Guwahati West, Jalukbari, Dispur, Dimoria'},
            {'name': 'Kamrup Rural', 'ac': 'Hajo, Rangia, Kamalpur, Boko, Chaygaon, Palasbari'},
            {'name': 'Dibrugarh', 'ac': 'Dibrugarh, Lahowal, Moran, Duliajan, Tingkhong, Naharkatia, Chabua'},
            {'name': 'Cachar (Silchar)', 'ac': 'Silchar, Sonai, Dholai, Udharbond, Lakhipur, Barkhola, Katigorah'},
            {'name': 'Jorhat', 'ac': 'Jorhat, Titabar, Mariani, Teok, Dergaon'},
            {'name': 'Nagaon', 'ac': 'Nagaon, Raha, Barhampur, Samaguri, Kaliabor, Rupohihat, Dhing, Batadroba'},
            {'name': 'Sonitpur (Tezpur)', 'ac': 'Tezpur, Dhekiajuli, Barchalla, Rangapara, Sootea, Biswanath, Gohpur, Behali'},
            {'name': 'Tinsukia', 'ac': 'Tinsukia, Digboi, Margherita, Doomdooma, Sadiya'},
            {'name': 'Sivasagar', 'ac': 'Sivasagar, Nazira, Amguri, Thowra, Mahmara'},
            {'name': 'Barpeta', 'ac': 'Barpeta, Jania, Baghbar, Sarukhetri, Chenga, Sorbhog'},
            {'name': 'Dhubri', 'ac': 'Dhubri, Gauripur, Golakganj, Bilasipara West, Bilasipara East'},
            {'name': 'Goalpara', 'ac': 'Goalpara East, Goalpara West, Dudhnoi, Jaleswar'},
            {'name': 'Karimganj', 'ac': 'Karimganj North, Karimganj South, Badarpur, Patharkandi, Ratabari'},
            {'name': 'Golaghat', 'ac': 'Golaghat, Bokakhat, Sarupathar, Khumtai'},
            {'name': 'Lakhimpur', 'ac': 'Lakhimpur, Naoboicha, Bihpuria, Dhakuakhana'},
            {'name': 'Dhemaji', 'ac': 'Dhemaji, Jonai'},
            {'name': 'Bongaigaon', 'ac': 'Bongaigaon, Abhayapuri North, Abhayapuri South'},
            {'name': 'Kokrajhar (BTR)', 'ac': 'Kokrajhar West, Kokrajhar East, Gossaigaon'},
            {'name': 'Baksa (BTR)', 'ac': 'Tamulpur, Barama, Chapaguri'},
            {'name': 'Chirang (BTR)', 'ac': 'Sidli, Bijni'},
            {'name': 'Udalguri (BTR)', 'ac': 'Udalguri, Mazbat, Panery, Kalaigaon'},
            {'name': 'Karbi Anglong (Diphu)', 'ac': 'Diphu, Baithalangso, Bokajan, Howraghat'},
            {'name': 'Dima Hasao (Haflong)', 'ac': 'Haflong'},
            {'name': 'Hailakandi', 'ac': 'Hailakandi, Katlicherra, Algapur'},
            {'name': 'Morigaon', 'ac': 'Morigaon, Jagiroad, Laharighat'},
            {'name': 'Nalbari', 'ac': 'Nalbari, Barkhetry, Dharmapur'},
            {'name': 'Darrang (Mangaldai)', 'ac': 'Mangaldai, Dalgaon, Sipajhar, Kalaigaon'},
            {'name': 'Hojai', 'ac': 'Hojai, Lumding, Jamunamukh'},
            {'name': 'Charaideo', 'ac': 'Sonari, Mahmora'},
            {'name': 'Majuli', 'ac': 'Majuli'},
            {'name': 'Biswanath', 'ac': 'Biswanath, Behali, Gohpur'},
            {'name': 'South Salmara-Mankachar', 'ac': 'Mankachar, South Salmara'},
            {'name': 'West Karbi Anglong', 'ac': 'Baithalangso'},
            {'name': 'Bajali', 'ac': 'Bhowanipur, Patacharkuchi'},
            {'name': 'Tamulpur', 'ac': 'Tamulpur'}
        ]
    },
    'uttarakhand-sir-voter-list': {
        'state_en': 'Uttarakhand',
        'state_hi': 'उत्तराखंड',
        'slug': 'uttarakhand-sir-voter-list',
        'title': 'Uttarakhand Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Uttarakhand Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceo.uk.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Uttarakhand',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी उत्तराखंड',
        'total_ac': 70,
        'total_districts': 13,
        'districts': [
            {'name': 'Dehradun', 'ac': 'Dehradun Cantt, Rajpur Road, Mussoorie, Raipur, Dharampur, Doiwala, Rishikesh, Sahaspur, Vikasnagar, Chakrata'},
            {'name': 'Haridwar', 'ac': 'Haridwar, Haridwar Rural, BHEL Ranipur, Jwalapur, Bhagwanpur, Roorkee, Piran Kaliyar, Khanpur, Manglaur, Laksar, Jhabrera'},
            {'name': 'Nainital (Haldwani)', 'ac': 'Haldwani, Nainital, Ramnagar, Bhimtal, Kaladhungi, Lalkuan'},
            {'name': 'Udham Singh Nagar (Rudrapur)', 'ac': 'Rudrapur, Kashipur, Kichha, Sitarganj, Khatima, Bajpur, Jaspur, Gadarpur, Nanakmatta'},
            {'name': 'Pauri Garhwal', 'ac': 'Pauri, Srinagar, Chaubattakhal, Lansdowne, Kotdwar, Yamkeshwar'},
            {'name': 'Tehri Garhwal', 'ac': 'Tehri, Dhanaulti, Ghali, Pratapnagar, Narendranagar, Devprayag'},
            {'name': 'Almora', 'ac': 'Almora, Ranikhet, Dwarahat, Someshwar, Jageshwar, Salt'},
            {'name': 'Pithoragarh', 'ac': 'Pithoragarh, Didihat, Gangolihat, Dharchula'},
            {'name': 'Chamoli (Gopeshwar)', 'ac': 'Badrinath, Tharali, Karnaprayag'},
            {'name': 'Rudraprayag', 'ac': 'Kedarnath, Rudraprayag'},
            {'name': 'Uttarkashi', 'ac': 'Gangotri, Yamunotri, Purola'},
            {'name': 'Bageshwar', 'ac': 'Bageshwar, Kapkot'},
            {'name': 'Champawat', 'ac': 'Champawat, Lohaghat'}
        ]
    },
    'himachal-pradesh-sir-voter-list': {
        'state_en': 'Himachal Pradesh',
        'state_hi': 'हिमाचल प्रदेश',
        'slug': 'himachal-pradesh-sir-voter-list',
        'title': 'Himachal Pradesh Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Himachal Pradesh Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceohimachal.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Himachal Pradesh',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी हिमाचल प्रदेश',
        'total_ac': 68,
        'total_districts': 12,
        'districts': [
            {'name': 'Shimla', 'ac': 'Shimla Urban, Shimla Rural, Kasumpti, Theog, Kusumpati, Rohru, Jubbal-Kotkhai, Chopal, Rampur'},
            {'name': 'Kangra (Dharamshala)', 'ac': 'Dharamshala, Kangra, Palampur, Nagrota, Shahpur, Jwalamukhi, Dehra, Jaswan-Pragpur, Nurpur, Fatehpur, Jawali, Baijnath, Sullah, Jaisinghpur, Indora'},
            {'name': 'Mandi', 'ac': 'Mandi, Sundernagar, Nachan, Balh, Sarkaghat, Jogindernagar, Darang, Karsog, Seraj'},
            {'name': 'Solan', 'ac': 'Solan, Kasauli, Nalagarh, Doon, Arki'},
            {'name': 'Sirmaur (Nahan)', 'ac': 'Nahan, Paonta Sahib, Pachhad, Sri Renukaji, Shillai'},
            {'name': 'Una', 'ac': 'Una, Haroli, Kutlehar, Gagret, Chintpurni'},
            {'name': 'Hamirpur', 'ac': 'Hamirpur, Nadaun, Sujanpur, Bhoranj, Barsar'},
            {'name': 'Kullu', 'ac': 'Kullu, Manali, Banjar, Anni'},
            {'name': 'Chamba', 'ac': 'Chamba, Dalhousie, Bhattiyat, Churah, Bharmour'},
            {'name': 'Bilaspur', 'ac': 'Bilaspur, Ghumarwin, Jhanduta, Sri Naina Deviji'},
            {'name': 'Kinnaur', 'ac': 'Kinnaur'},
            {'name': 'Lahaul and Spiti', 'ac': 'Lahaul and Spiti'}
        ]
    },
    'jammu-kashmir-sir-voter-list': {
        'state_en': 'Jammu & Kashmir (UT)',
        'state_hi': 'जम्मू और कश्मीर',
        'slug': 'jammu-kashmir-sir-voter-list',
        'title': 'Jammu Kashmir Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Jammu Kashmir Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceojk.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Jammu & Kashmir',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी जम्मू और कश्मीर',
        'total_ac': 90,
        'total_districts': 20,
        'districts': [
            {'name': 'Srinagar', 'ac': 'Hazratbal, Khanyar, Habbakadal, Lal Chowk, Channapora, Zadibal, Eidgah, Central Shalteng'},
            {'name': 'Jammu', 'ac': 'Jammu East, Jammu West, Jammu North, Jammu South, Bahu, RS Pura, Bishnah, Akhnoor, Chhamb, Nagrota, Marh'},
            {'name': 'Anantnag', 'ac': 'Anantnag, Anantnag West, Dooru, Kokernag, Shangus-Anantnag East, Bijbehara, Pahalgam'},
            {'name': 'Baramulla', 'ac': 'Baramulla, Sopore, Rafiabad, Uri, Pattan, Gulmarg, Wagoora-Kreeri'},
            {'name': 'Budgam', 'ac': 'Budgam, Beerwah, Khansahib, Chadoora, Charari Sharief'},
            {'name': 'Pulwama', 'ac': 'Pulwama, Pampore, Tral, Rajpora'},
            {'name': 'Kupwara', 'ac': 'Kupwara, Handwara, Karnah, Trehgam, Lolab, Langate'},
            {'name': 'Udhampur', 'ac': 'Udhampur West, Udhampur East, Chenani, Ramnagar'},
            {'name': 'Kathua', 'ac': 'Kathua, Hiranagar, Jasrota, Bani, Billawar, Basohli'},
            {'name': 'Rajouri', 'ac': 'Rajouri, Thannamandi, Darhal, Budhal, Nowshera, Kalakote-Sunderbani'},
            {'name': 'Poonch', 'ac': 'Haveli (Poonch), Mendhar, Surankote'},
            {'name': 'Doda', 'ac': 'Doda, Doda West, Bhaderwah'},
            {'name': 'Ramban', 'ac': 'Ramban, Banihal'},
            {'name': 'Kishtwar', 'ac': 'Kishtwar, Inderwal, Padder-Nagseni'},
            {'name': 'Reasi', 'ac': 'Reasi, Shri Mata Vaishno Devi, Gulabgarh'},
            {'name': 'Samba', 'ac': 'Samba, Vijaypur, Ramgarh'},
            {'name': 'Ganderbal', 'ac': 'Ganderbal, Kangan'},
            {'name': 'Bandipora', 'ac': 'Bandipora, Sonawari, Gurez'},
            {'name': 'Shopian', 'ac': 'Shopian, Zainapora'},
            {'name': 'Kulgam', 'ac': 'Kulgam, Devsar, Damhal Hanji Pora'}
        ]
    },
    'goa-sir-voter-list': {
        'state_en': 'Goa',
        'state_hi': 'गोवा',
        'slug': 'goa-sir-voter-list',
        'title': 'Goa Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Goa Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceogoa.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Goa',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी गोवा',
        'total_ac': 40,
        'total_districts': 2,
        'districts': [
            {'name': 'North Goa (Panaji)', 'ac': 'Panaji, Taleigao, Santa Cruz, St. Andre, Calangute, Saligao, Siolim, Aldona, Mapusa, Tivim, Porvorim, Mandrem, Pernem, Bicholim, Sanquelim, Poriem, Valpoi, Mayem, Cumbarjua'},
            {'name': 'South Goa (Margao)', 'ac': 'Margao, Fatorda, Curtorim, Nuvem, Benaulim, Navelim, Velim, Cuncolim, Quepem, Curchorem, Sanvordem, Sanguem, Canacona, Dabolim, Mormugao, Vasco Da Gama, Cortalim, Ponda, Shiroda, Marcaim'}
        ]
    },
    'tripura-sir-voter-list': {
        'state_en': 'Tripura',
        'state_hi': 'त्रिपुरा',
        'slug': 'tripura-sir-voter-list',
        'title': 'Tripura Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Tripura Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceotripura.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Tripura',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी त्रिपुरा',
        'total_ac': 60,
        'total_districts': 8,
        'districts': [
            {'name': 'West Tripura (Agartala)', 'ac': 'Agartala, Banamalipur, Town Bordowali, Ramnagar, Badharghat, Majlishpur, Mandai Bazar, Pratapgarh, Suryamaninagar, Bamutia, Barjala, Khayerpur, Mohanpur, Simna'},
            {'name': 'South Tripura (Belonia)', 'ac': 'Belonia, Santirbazar, Jolaibari, Manu, Hrishyamukh, Rajnagar'},
            {'name': 'Gomati (Udaipur)', 'ac': 'Radhakishorpur, Matarbari, Kakraban-Salgarh, Bagma, Karbook, Ampinagar'},
            {'name': 'Dhalai (Ambassa)', 'ac': 'Ambassa, Kamalpur, Surma, Chawamanu, Karamcherra, Raima Valley'},
            {'name': 'North Tripura (Dharmanagar)', 'ac': 'Dharmanagar, Kadamtala-Kurti, Bagbassa, Jubarajnagar, Panisagar, Pencharthal, Kanchanpur'},
            {'name': 'Unakoti (Kailashahar)', 'ac': 'Kailashahar, Chandipur, Pabiachhara, Fatikroy'},
            {'name': 'Khowai', 'ac': 'Khowai, Ashrambari, Teliamura, Krishnapur, Kalyanpur-Pramodenagar'},
            {'name': 'Sepahijala (Bishramganj)', 'ac': 'Bishalgarh, Golaghati, Charilam, Nalchar, Sonamura, Dhanpur, Boxanagar, Kamalasagar'}
        ]
    },
    'manipur-sir-voter-list': {
        'state_en': 'Manipur',
        'state_hi': 'मणिपुर',
        'slug': 'manipur-sir-voter-list',
        'title': 'Manipur Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Manipur Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceomanipur.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Manipur',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी मणिपुर',
        'total_ac': 60,
        'total_districts': 16,
        'districts': [
            {'name': 'Imphal West', 'ac': 'Sagolband, Uripok, Keishamthong, Singjamei, Yaiskul, Patsoi, Konthoujam, Lamsang, Sekmai, Langthabal, Mayang Imphal, Naoriya Pakhanglakpa, Wangoi'},
            {'name': 'Imphal East', 'ac': 'Khurai, Khetrigao, Thongju, Keirao, Andro, Lamlai, Heingang'},
            {'name': 'Thoubal', 'ac': 'Thoubal, Wangkhem, Heirok, Wangjing Tentha, Khangabok'},
            {'name': 'Bishnupur', 'ac': 'Bishnupur, Moirang, Thanga, Kumbi, Oinam, Nambol'},
            {'name': 'Churachandpur', 'ac': 'Churachandpur, Saikot, Singhat, Henglep, Tipaimukh, Thanlon'},
            {'name': 'Senapati', 'ac': 'Karong, Mao, Tadubi'},
            {'name': 'Ukhrul', 'ac': 'Ukhrul, Chingai'},
            {'name': 'Tamenglong', 'ac': 'Tamenglong, Tamei, Nungba'},
            {'name': 'Kangpokpi', 'ac': 'Kangpokpi, Saitu, Saikul'},
            {'name': 'Kakching', 'ac': 'Kakching, Hiyanglam, Sugnu'},
            {'name': 'Chandel', 'ac': 'Chandel, Tengnoupal'},
            {'name': 'Jiribam', 'ac': 'Jiribam'},
            {'name': 'Kamjong', 'ac': 'Phungyar'},
            {'name': 'Noney', 'ac': 'Nungba'},
            {'name': 'Pherzawl', 'ac': 'Tipaimukh, Thanlon'},
            {'name': 'Tengnoupal', 'ac': 'Tengnoupal'}
        ]
    },
    'meghalaya-sir-voter-list': {
        'state_en': 'Meghalaya',
        'state_hi': 'मेघालय',
        'slug': 'meghalaya-sir-voter-list',
        'title': 'Meghalaya Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Meghalaya Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceomeghalaya.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Meghalaya',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी मेघालय',
        'total_ac': 60,
        'total_districts': 12,
        'districts': [
            {'name': 'East Khasi Hills (Shillong)', 'ac': 'North Shillong, South Shillong, West Shillong, East Shillong, Pynthorumkhrah, Mawlai, Nongthymmai, Mylliem, Nongkrem, Sohiong, Mawphlang, Mawsynram, Shella, Pynursla, Sohra'},
            {'name': 'West Garo Hills (Tura)', 'ac': 'Tura, South Tura, North Tura, Rongram, Dadenggre, Phulbari, Rajabala, Selsella, Tikrikilla, Dalu, Rangsakona'},
            {'name': 'Ri-Bhoi (Nongpoh)', 'ac': 'Nongpoh, Jirang, Umsning, Umroi, Mawhati'},
            {'name': 'West Khasi Hills (Nongstoin)', 'ac': 'Nongstoin, Rambrai Jyrngam, Mawshynrut'},
            {'name': 'South West Khasi Hills (Mawkyrwat)', 'ac': 'Mawkyrwat, Ranikor'},
            {'name': 'Eastern West Khasi Hills (Mairang)', 'ac': 'Mairang, Mawthadraishan'},
            {'name': 'West Jaintia Hills (Jowai)', 'ac': 'Jowai, Nartiang, Raliang, Mowkaiaw, Amlarem'},
            {'name': 'East Jaintia Hills (Khliehriat)', 'ac': 'Khliehriat, Sutnga Saipung'},
            {'name': 'East Garo Hills (Williamnagar)', 'ac': 'Williamnagar, Songsak, Rongjeng'},
            {'name': 'South Garo Hills (Baghmara)', 'ac': 'Baghmara, Rongara Siju, Chokpot'},
            {'name': 'South West Garo Hills (Ampati)', 'ac': 'Ampati, Mahendraganj, Salmanpara'},
            {'name': 'North Garo Hills (Resubelpara)', 'ac': 'Resubelpara, Mendipathar, Kharkutta, Bajengdoba'}
        ]
    },
    'nagaland-sir-voter-list': {
        'state_en': 'Nagaland',
        'state_hi': 'नागालैंड',
        'slug': 'nagaland-sir-voter-list',
        'title': 'Nagaland Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Nagaland Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceonagaland.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Nagaland',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी नागालैंड',
        'total_ac': 60,
        'total_districts': 16,
        'districts': [
            {'name': 'Kohima', 'ac': 'Kohima Town, Northern Angami I, Northern Angami II, Western Angami, Southern Angami I, Southern Angami II, Tseminyu'},
            {'name': 'Dimapur', 'ac': 'Dimapur I, Dimapur II, Dimapur III'},
            {'name': 'Mokokchung', 'ac': 'Mokokchung Town, Alongtaki, Impur, Angetyongpang, Mongoya, Aonglenden, Koridang, Jangpetkong, Arkakong, Tuli'},
            {'name': 'Wokha', 'ac': 'Wokha, Sanis, Bhandari, Tyui'},
            {'name': 'Zunheboto', 'ac': 'Zunheboto, Suruhuto, Aghunato, Satakha, Atoizu, Akuluto'},
            {'name': 'Phek', 'ac': 'Phek, Meluri, Chozuba, Pfutsero, Chizami'},
            {'name': 'Mon', 'ac': 'Mon Town, Tizit, Tapi, Phomching, Tehok, Aboi, Tobu, Moka, Chen'},
            {'name': 'Tuensang', 'ac': 'Tuensang Sadar I, Tuensang Sadar II, Longkhim Chare, Shamator Chessore, Noklak, Thonoknyu'},
            {'name': 'Longleng', 'ac': 'Longleng, Tamlu'},
            {'name': 'Kiphire', 'ac': 'Pungro Kiphire, Seyochung Sitimi'},
            {'name': 'Peren', 'ac': 'Peren, Tening'},
            {'name': 'Chümoukedima', 'ac': 'Ghaspani I, Ghaspani II'},
            {'name': 'Niuland', 'ac': 'Ghaspani I'},
            {'name': 'Noklak', 'ac': 'Noklak, Thonoknyu'},
            {'name': 'Shamator', 'ac': 'Shamator Chessore'},
            {'name': 'Tseminyu', 'ac': 'Tseminyu'}
        ]
    },
    'mizoram-sir-voter-list': {
        'state_en': 'Mizoram',
        'state_hi': 'मिजोरम',
        'slug': 'mizoram-sir-voter-list',
        'title': 'Mizoram Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Mizoram Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceomizoram.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Mizoram',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी मिजोरम',
        'total_ac': 40,
        'total_districts': 11,
        'districts': [
            {'name': 'Aizawl', 'ac': 'Aizawl North I, Aizawl North II, Aizawl North III, Aizawl East I, Aizawl East II, Aizawl West I, Aizawl West II, Aizawl West III, Aizawl South I, Aizawl South II, Aizawl South III, Tuivawl, Chalfilh, Tawi'},
            {'name': 'Lunglei', 'ac': 'Lunglei North, Lunglei South, Lunglei East, Lunglei West, Thorang, West Tuipui'},
            {'name': 'Champhai', 'ac': 'Champhai North, Champhai South, East Tuipui'},
            {'name': 'Kolasib', 'ac': 'Kolasib, Tuirial, Serlui'},
            {'name': 'Serchhip', 'ac': 'Serchhip, Tuikum, Hrangturzo'},
            {'name': 'Mamit', 'ac': 'Mamit, Dampa, Hachhek'},
            {'name': 'Lawngtlai', 'ac': 'Lawngtlai West, Lawngtlai East, Tuichawng'},
            {'name': 'Siaha', 'ac': 'Siaha, Palak'},
            {'name': 'Hnahthial', 'ac': 'South Tuipui'},
            {'name': 'Khawzawl', 'ac': 'Khawzawl'},
            {'name': 'Saitual', 'ac': 'Saitual'}
        ]
    },
    'arunachal-pradesh-sir-voter-list': {
        'state_en': 'Arunachal Pradesh',
        'state_hi': 'अरुणाचल प्रदेश',
        'slug': 'arunachal-pradesh-sir-voter-list',
        'title': 'Arunachal Pradesh Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Arunachal Pradesh Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceoarunachal.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Arunachal Pradesh',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी अरुणाचल प्रदेश',
        'total_ac': 60,
        'total_districts': 26,
        'districts': [
            {'name': 'Papum Pare (Itanagar)', 'ac': 'Itanagar, Doimukh, Sagalee'},
            {'name': 'Changlang', 'ac': 'Changlang North, Changlang South, Bordumsa-Diyun, Miao, Jairampur, Nampong'},
            {'name': 'West Kameng (Bomdila)', 'ac': 'Bomdila, Dirang, Kalaktang, Thrizino-Buragaon'},
            {'name': 'East Kameng (Seppa)', 'ac': 'Seppa East, Seppa West, Pakke-Kessang, Bameng, Chayangtajo'},
            {'name': 'Tawang', 'ac': 'Tawang, Mukto, Lumla'},
            {'name': 'Lower Subansiri (Ziro)', 'ac': 'Ziro-Hapoli, Yachuli'},
            {'name': 'Upper Subansiri (Daporijo)', 'ac': 'Daporijo, Dumporijo, Taliha, Nacho'},
            {'name': 'West Siang (Aalo)', 'ac': 'Aalo East, Aalo West, Liromoba'},
            {'name': 'East Siang (Pasighat)', 'ac': 'Pasighat East, Pasighat West, Mebo'},
            {'name': 'Lohit (Tezu)', 'ac': 'Tezu, Sunpura'},
            {'name': 'Namsai', 'ac': 'Namsai, Lekang, Chowkham'},
            {'name': 'Tirap (Khonsa)', 'ac': 'Khonsa East, Khonsa West, Borduria-Bogapani'},
            {'name': 'Longding', 'ac': 'Longding-Pumao, Pongchau-Wakka, Kanubari'},
            {'name': 'Anjaw (Hawai)', 'ac': 'Hayuliang'},
            {'name': 'Dibang Valley (Anini)', 'ac': 'Anini'},
            {'name': 'Lower Dibang Valley (Roing)', 'ac': 'Roing, Dambuk'},
            {'name': 'Kurung Kumey (Koloriang)', 'ac': 'Koloriang, Nyapin, Palin'},
            {'name': 'Kra Daadi (Jamin)', 'ac': 'Tali, Palin, Chayang Tajo'},
            {'name': 'Upper Siang (Yingkiong)', 'ac': 'Tuting-Yingkiong, Mariyang-Geku'},
            {'name': 'Siang (Pangin)', 'ac': 'Pangin, Rumgong'},
            {'name': 'Lower Siang (Likabali)', 'ac': 'Likabali, Nari-Koyu'},
            {'name': 'Pakke Kessang', 'ac': 'Pakke-Kessang'},
            {'name': 'Kamle (Raga)', 'ac': 'Raga'},
            {'name': 'Leparada (Basar)', 'ac': 'Basar'},
            {'name': 'Shi Yomi (Tato)', 'ac': 'Mechuka'},
            {'name': 'Itanagar Capital Complex', 'ac': 'Itanagar'}
        ]
    },
    'sikkim-sir-voter-list': {
        'state_en': 'Sikkim',
        'state_hi': 'सिक्किम',
        'slug': 'sikkim-sir-voter-list',
        'title': 'Sikkim Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Sikkim Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceosikkim.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Sikkim',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी सिक्किम',
        'total_ac': 32,
        'total_districts': 6,
        'districts': [
            {'name': 'East Sikkim (Gangtok)', 'ac': 'Gangtok, Upper Burtuk, Arithang, Chujachen, Gnathang-Machong, Namcheybung, Shyari, Martam-Rumtek, Khamdong-Singtam'},
            {'name': 'West Sikkim (Gyalshing)', 'ac': 'Gyalshing-Barnyak, Maneybung-Dentam, Yangthang, Yuksom-Tashiding, Rinchenpong, Daramdin'},
            {'name': 'South Sikkim (Namchi)', 'ac': 'Namchi-Singhithang, Poklok-Kamrang, Barfung, Rangang-Yangang, Tumen-Lingi, Namthang-Rateypani, Melli'},
            {'name': 'North Sikkim (Mangan)', 'ac': 'Kabi Lungchok, Djongu, Lachen Mangan'},
            {'name': 'Pakyong', 'ac': 'Pakyong, Rhenock, Chujachen, Gnathang-Machong'},
            {'name': 'Soreng', 'ac': 'Soreng-Chakung, Daramdin, Rinchenpong'}
        ]
    }
}
print('Batch 5 data ready (South & NE states)...')

