# -*- coding: utf-8 -*-
BATCH_4 = {
    'west-bengal-sir-voter-list': {
        'state_en': 'West Bengal',
        'state_hi': 'पश्चिम बंगाल',
        'slug': 'west-bengal-sir-voter-list',
        'title': 'West Bengal Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'West Bengal Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceowestbengal.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) West Bengal',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी पश्चिम बंगाल',
        'total_ac': 294,
        'total_districts': 23,
        'districts': [
            {'name': 'Kolkata', 'ac': 'Kolkata Port, Bhabanipur, Rashbehari, Ballygunge, Chowrangee, Entally, Beleghata, Jorasanko, Shyampukur, Maniktala, Kashipur-Belgachhia'},
            {'name': 'North 24 Parganas', 'ac': 'Barasat, Bidhannagar, Rajarhat Gopalpur, Rajarhat New Town, Dum Dum, Madhyamgram, Habra, Ashoknagar, Naihati, Bhatpara, Jagaddal, Noapara, Barrackpur, Khardaha, Panihati, Kamarhati, Baranagar'},
            {'name': 'South 24 Parganas', 'ac': 'Jadavpur, Tollygunge, Behala Purba, Behala Paschim, Maheshtala, Budge Budge, Metiabruz, Sonarpur Dakshin, Sonarpur Uttar, Baruipur Purba, Baruipur Paschim, Canning, Gosaba, Basanti, Kulpi, Diamond Harbour, Kakdwip, Sagar'},
            {'name': 'Howrah', 'ac': 'Howrah Uttar, Howrah Madhya, Howrah Dakshin, Shibpur, Bally, Uttarpara, Panchla, Uluberia, Amta, Bagnan, Shyampur'},
            {'name': 'Hooghly', 'ac': 'Chinsurah, Chandannagar, Singur, Serampore, Champdani, Tarakeswar, Arambagh, Pursurah, Khanakul, Haripal, Balagarh, Pandua'},
            {'name': 'Purba Bardhaman', 'ac': 'Bardhaman Dakshin, Bardhaman Uttar, Memari, Kalna, Katwa, Purbasthali, Ausgram, Bhatar, Galsi, Raina, Jamalpur'},
            {'name': 'Paschim Bardhaman', 'ac': 'Asansol Uttar, Asansol Dakshin, Raniganj, Jamuria, Kulti, Durgapur Purba, Durgapur Paschim, Pandabeswar'},
            {'name': 'Murshidabad', 'ac': 'Berhampore, Murshidabad, Lalbagh, Jangipur, Raghunathganj, Kandi, Domkal, Raninagar, Jalangi, Hariharpara, Nowda, Beldanga, Bharatpur, Rejinagar'},
            {'name': 'Nadia', 'ac': 'Krishnanagar Uttar, Krishnanagar Dakshin, Nabadwip, Santipur, Ranaghat Uttar Paschim, Ranaghat Dakshin, Kalyani, Haringhata, Chapra, Tehatta, Karimpur, Nakashipara, Kaliganj'},
            {'name': 'Malda', 'ac': 'English Bazar, Old Malda, Habibpur, Gazole, Chanchal, Harischandrapur, Malatipur, Ratua, Manikchak, Sujapur, Baisnabnagar, Mothabari'},
            {'name': 'Birbhum', 'ac': 'Suri, Bolpur, Rampurhat, Sainthia, Dubrajpur, Mayureswar, Labpur, Nanoor, Murarai, Nalhati, Hansan'},
            {'name': 'Bankura', 'ac': 'Bankura, Bishnupur, Onda, Chhatna, Saltora, Barjora, Kotulpur, Sonamukhi, Indas, Taldangra, Raipur, Ranibandh'},
            {'name': 'Purulia', 'ac': 'Purulia, Manbazar, Kashipur, Para, Raghunathpur, Balarampur, Baghmundi, Joypur, Bandwan'},
            {'name': 'Paschim Medinipur', 'ac': 'Midnapore, Kharagpur Sadar, Kharagpur, Debra, Pingla, Sabang, Dantan, Narayangarh, Keshpur, Garbeta, Salboni, Chandrakona, Ghatal'},
            {'name': 'Purba Medinipur', 'ac': 'Tamluk, Haldia, Nandigram, Contai Uttar, Contai Dakshin, Egra, Ramnagar, Panskura, Moyna, Chandipur, Bhagabanpur, Khejuri, Patashpur'},
            {'name': 'Jhargram', 'ac': 'Jhargram, Gopiballavpur, Nayagram, Binpur'},
            {'name': 'Jalpaiguri', 'ac': 'Jalpaiguri, Rajganj, Dabgram-Phulbari, Maynaguri, Dhupguri, Mal, Kranti'},
            {'name': 'Darjeeling', 'ac': 'Darjeeling, Kurseong, Siliguri, Matigara-Naxalbari, Phansidewa'},
            {'name': 'Kalimpong', 'ac': 'Kalimpong'},
            {'name': 'Alipurduar', 'ac': 'Alipurduars, Falakata, Madarihat, Kalchini, Kumargram'},
            {'name': 'Cooch Behar', 'ac': 'Cooch Behar Uttar, Cooch Behar Dakshin, Dinhata, Sitai, Mathabhanga, Mekliganj, Sitalkuchi, Natabari, Tufanganj'},
            {'name': 'Uttar Dinajpur', 'ac': 'Raiganj, Kaliaganj, Hemtabad, Itahar, Karandighi, Islampur, Goalpokhar, Chakulia, Chopra'},
            {'name': 'Dakshin Dinajpur', 'ac': 'Balurghat, Gangarampur, Harirampur, Kushmandi, Kumarganj, Tapan'}
        ]
    },
    'jharkhand-sir-voter-list': {
        'state_en': 'Jharkhand',
        'state_hi': 'झारखंड',
        'slug': 'jharkhand-sir-voter-list',
        'title': 'Jharkhand Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Jharkhand Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceojharkhand.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Jharkhand',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी झारखंड',
        'total_ac': 81,
        'total_districts': 24,
        'districts': [
            {'name': 'Ranchi', 'ac': 'Ranchi, Hatia, Kanke, Mandar, Silli, Khijri, Tamar'},
            {'name': 'East Singhbhum (Jamshedpur)', 'ac': 'Jamshedpur East, Jamshedpur West, Jugsalai, Potka, Ghatsila, Baharagora'},
            {'name': 'Dhanbad', 'ac': 'Dhanbad, Jharia, Sindri, Nirsa, Baghmara, Tundi'},
            {'name': 'Bokaro', 'ac': 'Bokaro, Bermo, Chandankiyari, Gomia'},
            {'name': 'Hazaribagh', 'ac': 'Hazaribagh, Barkagaon, Barhi, Mandu'},
            {'name': 'Ramgarh', 'ac': 'Ramgarh, Barkatha'},
            {'name': 'Palamu (Medininagar)', 'ac': 'Daltonganj, Bishrampur, Chhatarpur, Hussainabad, Panki'},
            {'name': 'Giridih', 'ac': 'Giridih, Gandey, Dumri, Bagodar, Dhanwar, Jamua'},
            {'name': 'Deoghar', 'ac': 'Deoghar, Madhupur, Sarath'},
            {'name': 'Dumka', 'ac': 'Dumka, Jama, Jarmundi, Shikaripara'},
            {'name': 'Godda', 'ac': 'Godda, Mahagama, Poreyahat'},
            {'name': 'Sahebganj', 'ac': 'Rajmahal, Borio, Barhait'},
            {'name': 'Pakur', 'ac': 'Pakur, Litipara, Maheshpur'},
            {'name': 'Jamtara', 'ac': 'Jamtara, Nala'},
            {'name': 'West Singhbhum (Chaibasa)', 'ac': 'Chaibasa, Jagannathpur, Manoharpur, Chakradharpur, Majhgaon'},
            {'name': 'Seraikela Kharsawan', 'ac': 'Seraikela, Kharsawan, Ichagarh'},
            {'name': 'Garhwa', 'ac': 'Garhwa, Bhawanathpur'},
            {'name': 'Latehar', 'ac': 'Latehar, Manika'},
            {'name': 'Chatra', 'ac': 'Chatra, Simaria'},
            {'name': 'Koderma', 'ac': 'Koderma'},
            {'name': 'Lohardaga', 'ac': 'Lohardaga'},
            {'name': 'Gumla', 'ac': 'Gumla, Sisai, Bishunpur'},
            {'name': 'Simdega', 'ac': 'Simdega, Kolebira'},
            {'name': 'Khunti', 'ac': 'Khunti, Torpa'}
        ]
    },
    'chhattisgarh-sir-voter-list': {
        'state_en': 'Chhattisgarh',
        'state_hi': 'छत्तीसगढ़',
        'slug': 'chhattisgarh-sir-voter-list',
        'title': 'Chhattisgarh Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Chhattisgarh Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceochhattisgarh.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Chhattisgarh',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी छत्तीसगढ़',
        'total_ac': 90,
        'total_districts': 33,
        'districts': [
            {'name': 'Raipur', 'ac': 'Raipur City North, Raipur City South, Raipur City West, Raipur Rural, Arang, Abhanpur, Dharsiwa'},
            {'name': 'Durg', 'ac': 'Durg City, Durg Rural, Bhilai Nagar, Vaishali Nagar, Patan, Ahiwara'},
            {'name': 'Bilaspur', 'ac': 'Bilaspur, Bilha, Belha, Kota, Takhatpur, Masturi'},
            {'name': 'Rajnandgaon', 'ac': 'Rajnandgaon, Dongargaon, Dongargarh, Khujji'},
            {'name': 'Korba', 'ac': 'Korba, Katghora, Pali-Tanakhar, Rampur'},
            {'name': 'Raigarh', 'ac': 'Raigarh, Kharsia, Sarangarh, Lailunga, Dharamjaigarh'},
            {'name': 'Janjgir-Champa', 'ac': 'Janjgir-Champa, Akaltara, Pamgarh, Sakti, Jaijaipur, Chandrapur'},
            {'name': 'Bastar (Jagdalpur)', 'ac': 'Jagdalpur, Bastar, Chitrakot'},
            {'name': 'Surguja (Ambikapur)', 'ac': 'Ambikapur, Sitapur, Lundra'},
            {'name': 'Dhamtari', 'ac': 'Dhamtari, Kurud, Sihawa'},
            {'name': 'Mahasamund', 'ac': 'Mahasamund, Saraipali, Basna, Khallari'},
            {'name': 'Balod', 'ac': 'Balod, Sanod, Gunderdehi, Dondi Lohara'},
            {'name': 'Bemetara', 'ac': 'Bemetara, Saja, Nawagarh'},
            {'name': 'Kawardha (Kabirdham)', 'ac': 'Kawardha, Pandariya'},
            {'name': 'Kanker (North Bastar)', 'ac': 'Kanker, Bhanupratappur, Antagarh'},
            {'name': 'Dantewada (South Bastar)', 'ac': 'Dantewada'},
            {'name': 'Sukma', 'ac': 'Konta'},
            {'name': 'Bijapur', 'ac': 'Bijapur'},
            {'name': 'Narayanpur', 'ac': 'Narayanpur'},
            {'name': 'Kondagaon', 'ac': 'Kondagaon, Keshkal'},
            {'name': 'Surajpur', 'ac': 'Bhatgaon, Premnagar, Pratappur'},
            {'name': 'Balrampur', 'ac': 'Ramanujganj, Samri'},
            {'name': 'Koriya (Baikunthpur)', 'ac': 'Baikunthpur, Bharatpur-Sonhat'},
            {'name': 'Manendragarh-Chirmiri-Bharatpur', 'ac': 'Manendragarh, Chirmiri'},
            {'name': 'Jashpur', 'ac': 'Jashpur, Kunkuri, Pathalgaon'},
            {'name': 'Mungeli', 'ac': 'Mungeli, Lormi'},
            {'name': 'Gariaband', 'ac': 'Rajim, Bindranawagarh'},
            {'name': 'Baloda Bazar', 'ac': 'Baloda Bazar, Bhatapara, Kasdol'},
            {'name': 'Gaurela-Pendra-Marwahi', 'ac': 'Marwahi'},
            {'name': 'Sakti', 'ac': 'Sakti, Jaijaipur'},
            {'name': 'Sarangarh-Bilaigarh', 'ac': 'Sarangarh, Bilaigarh'},
            {'name': 'Khairagarh-Chhuikhadan-Gandai', 'ac': 'Khairagarh'},
            {'name': 'Mohla-Manpur-Ambagarh Chowki', 'ac': 'Mohla-Manpur'}
        ]
    },
    'odisha-sir-voter-list': {
        'state_en': 'Odisha',
        'state_hi': 'ओडिशा',
        'slug': 'odisha-sir-voter-list',
        'title': 'Odisha Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Odisha Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceoorissa.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Odisha',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी ओडिशा',
        'total_ac': 147,
        'total_districts': 30,
        'districts': [
            {'name': 'Khordha (Bhubaneswar)', 'ac': 'Bhubaneswar Central, Bhubaneswar North, Ekamra-Bhubaneswar, Jatani, Jayadev, Khurda, Begunia, Chilika'},
            {'name': 'Cuttack', 'ac': 'Cuttack City, Barabati-Cuttack, Choudwar-Cuttack, Cuttack Sadar, Salipur, Mahanga, Banki, Athagarh, Badamba, Niali'},
            {'name': 'Ganjam (Berhampur)', 'ac': 'Berhampur, Gopalpur, Chhatrapur, Hinjili, Digapahandi, Sorada, Sanakhemundi, Aska, Surada, Polasara, Kabisuryanagar, Khallikote, Bhanjanagar'},
            {'name': 'Puri', 'ac': 'Puri, Brahmagiri, Satyabadi, Pipili, Nimapara, Kakatpur'},
            {'name': 'Balasore (Baleswar)', 'ac': 'Balasore, Remuna, Nilgiri, Basta, Jaleswar, Bhograi, Soro, Simulia'},
            {'name': 'Bhadrak', 'ac': 'Bhadrak, Basudevpur, Dhamnagar, Bhandaripokhari, Chandabali'},
            {'name': 'Mayurbhanj (Baripada)', 'ac': 'Baripada, Morada, Badasahi, Jashipur, Saraskana, Rairangpur, Bangriposi, Karanjia, Udala'},
            {'name': 'Sundargarh (Rourkela)', 'ac': 'Rourkela, Raghunathpali, Biramitrapur, Sundargarh, Talsara, Rajgangpur, Bonai'},
            {'name': 'Sambalpur', 'ac': 'Sambalpur, Rengali, Rairakhol, Kuchinda'},
            {'name': 'Bargarh', 'ac': 'Bargarh, Padampur, Bijepur, Attabira, Bhatli'},
            {'name': 'Bolangir (Balangir)', 'ac': 'Balangir, Titlagarh, Kantabanji, Patnagarh, Loisingha'},
            {'name': 'Kalahandi (Bhawanipatna)', 'ac': 'Bhawanipatna, Junagarh, Dharmagarh, Lanjigarh, Narla'},
            {'name': 'Koraput', 'ac': 'Koraput, Jeypore, Kotpad, Pottangi, Lakshmipur'},
            {'name': 'Rayagada', 'ac': 'Rayagada, Gunupur, Bissam Cuttack'},
            {'name': 'Nabarangpur', 'ac': 'Nabarangpur, Dabugam, Kotpad, Umerkote, Jharigam'},
            {'name': 'Malkangiri', 'ac': 'Malkangiri, Chitrakonda'},
            {'name': 'Kandhamal (Phulbani)', 'ac': 'Phulbani, G. Udayagiri, Baliguda'},
            {'name': 'Angul', 'ac': 'Angul, Talcher, Chhendipada, Pallahara, Athamallik'},
            {'name': 'Dhenkanal', 'ac': 'Dhenkanal, Hindol, Kamakhyanagar, Parjanga'},
            {'name': 'Kendujhar (Keonjhar)', 'ac': 'Keonjhar, Champua, Telkoi, Ghasipura, Anandapur, Patna'},
            {'name': 'Jajpur', 'ac': 'Jajpur, Korei, Sukinda, Dharmasala, Barchana, Bari, Binjharpur'},
            {'name': 'Kendrapara', 'ac': 'Kendrapara, Patkura, Mahakalapada, Aul, Rajnagar'},
            {'name': 'Jagatsinghpur', 'ac': 'Jagatsinghpur, Paradeep, Tirtol, Balikuda-Erasama'},
            {'name': 'Nayagarh', 'ac': 'Nayagarh, Ranpur, Khandapada, Daspalla'},
            {'name': 'Gajapati (Paralakhemundi)', 'ac': 'Paralakhemundi, Mohana'},
            {'name': 'Nuapada', 'ac': 'Nuapada, Khariar'},
            {'name': 'Subarnapur (Sonepur)', 'ac': 'Sonepur, Birmaharajpur'},
            {'name': 'Boudh', 'ac': 'Boudh, Kantamal'},
            {'name': 'Jharsuguda', 'ac': 'Jharsuguda, Brajarajnagar'},
            {'name': 'Deogarh (Debagarh)', 'ac': 'Deogarh'}
        ]
    }
}
print('Batch 4 data ready (WB, Jharkhand, CG, Odisha)...')
