# -*- coding: utf-8 -*-
BATCH_3 = {
    'gujarat-sir-voter-list': {
        'state_en': 'Gujarat',
        'state_hi': 'गुजरात',
        'slug': 'gujarat-sir-voter-list',
        'title': 'Gujarat Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Gujarat Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceo.gujarat.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Gujarat',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी गुजरात',
        'total_ac': 182,
        'total_districts': 33,
        'districts': [
            {'name': 'Ahmedabad', 'ac': 'Ghatlodia, Vejalpur, Vatva, Ellisbridge, Naranpura, Nikol, Naroda, Thakkarbapa Nagar, Bapunagar, Amraiwadi, Dariapur, Jamalpur-Khadia, Maninagar, Danilimda, Sabarmati, Asarwa, Daskroi, Dholka, Dhandhuka, Sanand, Viramgam'},
            {'name': 'Surat', 'ac': 'Surat City North, Surat City West, Surat City East, Majura, Katargam, Varachha Road, Karanj, Limbayat, Udhana, Choryasi, Olpad, Mangrol, Mandvi, Kamrej, Bardoli, Mahuva'},
            {'name': 'Vadodara', 'ac': 'Vadodara City, Sayajigunj, Akota, Raopura, Manjalpur, Savli, Vaghodia, Dabhoi, Karjan, Padra'},
            {'name': 'Rajkot', 'ac': 'Rajkot East, Rajkot West, Rajkot South, Rajkot Rural, Jasdan, Gondal, Jetpur, Dhoraji'},
            {'name': 'Bhavnagar', 'ac': 'Bhavnagar East, Bhavnagar West, Bhavnagar Rural, Mahuva, Talaja, Gariadhar, Palitana'},
            {'name': 'Jamnagar', 'ac': 'Jamnagar Rural, Jamnagar North, Jamnagar South, Kalavad, Jamjodhpur'},
            {'name': 'Gandhinagar', 'ac': 'Gandhinagar North, Gandhinagar South, Mansa, Kalol, Dehgam'},
            {'name': 'Junagadh', 'ac': 'Junagadh City, Visavadar, Manavadar, Mangrol, Keshod'},
            {'name': 'Anand', 'ac': 'Anand, Borsad, Anklav, Umreth, Petlad, Sojitra, Khambhat'},
            {'name': 'Kheda (Nadiad)', 'ac': 'Nadiad, Matar, Mehmedabad, Mahudha, Thasra, Kapadvanj'},
            {'name': 'Mehsana', 'ac': 'Mehsana, Kadi, Visnagar, Bechraji, Vijapur, Vadnagar, Kheralu'},
            {'name': 'Banaskantha (Palanpur)', 'ac': 'Palanpur, Vav, Tharad, Dhanera, Danta, Vadgam, Deesa, Deodar, Kankrej'},
            {'name': 'Patan', 'ac': 'Patan, Radhanpur, Chanasma, Sidhpur'},
            {'name': 'Sabarkantha (Himmatnagar)', 'ac': 'Himmatnagar, Idar, Khedbrahma, Prantij'},
            {'name': 'Aravalli (Modasa)', 'ac': 'Modasa, Bhiloda, Bayad'},
            {'name': 'Bharuch', 'ac': 'Bharuch, Ankleshwar, Vagra, Jhagadia, Jambusar'},
            {'name': 'Navsari', 'ac': 'Navsari, Jalalpore, Gandevi, Vansda'},
            {'name': 'Valsad', 'ac': 'Valsad, Pardi, Umbergaon, Dharampur, Kaprada'},
            {'name': 'Panchmahal (Godhra)', 'ac': 'Godhra, Shehra, Morva Hadaf, Halol, Kalol'},
            {'name': 'Dahod', 'ac': 'Dahod, Limkheda, Jhalod, Fatepura, Garbada, Devgadhbaria'},
            {'name': 'Mahisagar (Lunawada)', 'ac': 'Lunawada, Santrampur, Balasinor'},
            {'name': 'Amreli', 'ac': 'Amreli, Dhari, Lathi, Savarkundla, Rajula'},
            {'name': 'Surendranagar', 'ac': 'Wadhwan, Limbdi, Chotila, Dhrangadhra, Dasada'},
            {'name': 'Morbi', 'ac': 'Morbi, Wankaner, Tankara'},
            {'name': 'Porbandar', 'ac': 'Porbandar, Kutiyana'},
            {'name': 'Devbhumi Dwarka', 'ac': 'Dwarka, Khambhalia'},
            {'name': 'Gir Somnath (Veraval)', 'ac': 'Somnath, Talala, Kodinar, Una'},
            {'name': 'Botad', 'ac': 'Botad, Gadhada'},
            {'name': 'Narmada (Rajpipla)', 'ac': 'Nandod, Dediapada'},
            {'name': 'Tapi (Vyara)', 'ac': 'Vyara, Nizar'},
            {'name': 'Dang (Ahwa)', 'ac': 'Dangs'},
            {'name': 'Kutch (Bhuj)', 'ac': 'Bhuj, Abdasa, Mandvi, Anjar, Gandhidham, Rapar'},
            {'name': 'Chhota Udaipur', 'ac': 'Chhota Udaipur, Jetpur, Sankheda'}
        ]
    },
    'haryana-sir-voter-list': {
        'state_en': 'Haryana',
        'state_hi': 'हरियाणा',
        'slug': 'haryana-sir-voter-list',
        'title': 'Haryana Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Haryana Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceoharyana.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Haryana',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी हरियाणा',
        'total_ac': 90,
        'total_districts': 22,
        'districts': [
            {'name': 'Gurugram (Gurgaon)', 'ac': 'Gurgaon, Badshahpur, Pataudi, Sohna'},
            {'name': 'Faridabad', 'ac': 'Faridabad, Faridabad NIT, Badkhal, Ballabhgarh, Tigaon, Prithla'},
            {'name': 'Hisar', 'ac': 'Hisar, Adampur, Uklana, Narnaund, Hansi, Barwala, Nalwa'},
            {'name': 'Rohtak', 'ac': 'Rohtak, Garhi Sampla-Kiloi, Kalanaur, Meham'},
            {'name': 'Karnal', 'ac': 'Karnal, Gharaunda, Indri, Nilokheri, Assandh'},
            {'name': 'Panipat', 'ac': 'Panipat Rural, Panipat City, Israna, Samalkha'},
            {'name': 'Sonipat', 'ac': 'Sonipat, Ganaur, Rai, Kharkhauda, Gohana, Baroda'},
            {'name': 'Ambala', 'ac': 'Ambala City, Ambala Cantt, Mullana, Naraingarh'},
            {'name': 'Panchkula', 'ac': 'Panchkula, Kalka'},
            {'name': 'Yamunanagar', 'ac': 'Yamunanagar, Jagadhri, Sadhaura, Radaur'},
            {'name': 'Kurukshetra', 'ac': 'Thanesar, Ladwa, Shahbad, Pehowa'},
            {'name': 'Kaithal', 'ac': 'Kaithal, Pundri, Kalayat, Guhla'},
            {'name': 'Jind', 'ac': 'Jind, Julana, Safidon, Uchana Kalan, Narwana'},
            {'name': 'Sirsa', 'ac': 'Sirsa, Ellenabad, Rania, Kalanwali, Dabwali'},
            {'name': 'Fatehabad', 'ac': 'Fatehabad, Tohana, Ratia'},
            {'name': 'Bhiwani', 'ac': 'Bhiwani, Tosham, Bawani Khera, Loharu'},
            {'name': 'Charkhi Dadri', 'ac': 'Dadri, Badhra'},
            {'name': 'Jhajjar', 'ac': 'Jhajjar, Bahadurgarh, Badli, Beri'},
            {'name': 'Rewari', 'ac': 'Rewari, Bawal, Kosli'},
            {'name': 'Mahendragarh (Narnaul)', 'ac': 'Narnaul, Mahendragarh, Ateli, Nangal Chaudhry'},
            {'name': 'Palwal', 'ac': 'Palwal, Hodal, Hathin'},
            {'name': 'Nuh (Mewat)', 'ac': 'Nuh, Ferozepur Jhirka, Punhana'}
        ]
    },
    'punjab-sir-voter-list': {
        'state_en': 'Punjab',
        'state_hi': 'पंजाब',
        'slug': 'punjab-sir-voter-list',
        'title': 'Punjab Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Punjab Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceopunjab.gov.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Punjab',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी पंजाब',
        'total_ac': 117,
        'total_districts': 23,
        'districts': [
            {'name': 'Ludhiana', 'ac': 'Ludhiana East, Ludhiana South, Ludhiana Central, Ludhiana West, Ludhiana North, Gill, Atam Nagar, Payal, Khanna, Samrala, Sahnewal, Dakha, Raikot, Jagraon'},
            {'name': 'Amritsar', 'ac': 'Amritsar North, Amritsar Central, Amritsar South, Amritsar East, Amritsar West, Rajasansi, Majitha, Jandiala, Attari, Baba Bakala, Ajnala'},
            {'name': 'Jalandhar', 'ac': 'Jalandhar Central, Jalandhar North, Jalandhar West, Jalandhar Cantt, Kartarpur, Adampur, Nakodar, Shahkot, Phillaur'},
            {'name': 'Patiala', 'ac': 'Patiala Urban, Patiala Rural, Sanaur, Samana, Nabha, Rajpura, Ghanaur, Shutrana'},
            {'name': 'Bathinda', 'ac': 'Bathinda Urban, Bathinda Rural, Bhucho Mandi, Talwandi Sabo, Maur, Rampura Phul'},
            {'name': 'SAS Nagar (Mohali)', 'ac': 'Mohali, Kharar, Dera Bassi'},
            {'name': 'Hoshiarpur', 'ac': 'Hoshiarpur, Chabbewal, Dasuya, Urmar, Mukerian, Sham Chaurasi, Garhshankar'},
            {'name': 'Gurdaspur', 'ac': 'Gurdaspur, Batala, Dera Baba Nanak, Dina Nagar, Fatehgarh Churian, Qadian, Sri Hargobindpur'},
            {'name': 'Pathankot', 'ac': 'Pathankot, Sujanpur, Bhoa'},
            {'name': 'Firozpur', 'ac': 'Firozpur City, Firozpur Rural, Guru Har Sahai, Zira'},
            {'name': 'Fazilka', 'ac': 'Fazilka, Abohar, Jalalabad, Balluana'},
            {'name': 'Muktsar (Sri Muktsar Sahib)', 'ac': 'Muktsar, Malout, Gidderbaha, Lambi'},
            {'name': 'Faridkot', 'ac': 'Faridkot, Kotkapura, Jaitu'},
            {'name': 'Moga', 'ac': 'Moga, Baghapurana, Nihal Singh Wala, Dharamkot'},
            {'name': 'Sangrur', 'ac': 'Sangrur, Sunam, Dirba, Lehra, Dhuri'},
            {'name': 'Barnala', 'ac': 'Barnala, Mehal Kalan, Bhadaur'},
            {'name': 'Mansa', 'ac': 'Mansa, Budhlada, Sardulgarh'},
            {'name': 'Kapurthala', 'ac': 'Kapurthala, Phagwara, Bholath, Sultanpur Lodhi'},
            {'name': 'Tarn Taran', 'ac': 'Tarn Taran, Patti, Khemkaran, Khadoor Sahib'},
            {'name': 'Rupnagar (Ropar)', 'ac': 'Rupnagar, Anandpur Sahib, Chamkaur Sahib'},
            {'name': 'Fatehgarh Sahib', 'ac': 'Fatehgarh Sahib, Amloh, Bassi Pathana'},
            {'name': 'SBS Nagar (Nawanshahr)', 'ac': 'Nawanshahr, Banga, Balachaur'},
            {'name': 'Malerkotla', 'ac': 'Malerkotla, Amargarh'}
        ]
    }
}
print('Batch 3 data ready (Gujarat, Haryana, Punjab)...')
