import os
import glob
import re
import json
import sys

sys.stdout.reconfigure(encoding='utf-8')

# State Specific Portals & Metadata Directory
STATE_METADATA = {
    "andaman-nicobar": {
        "nameEn": "Andaman & Nicobar Islands",
        "nameHi": "अंडमान और निकोबार",
        "portalName": "e-District Andaman Portal",
        "portalUrl": "https://edistrict.andaman.gov.in",
        "fee": "₹25",
        "timeline": "7 to 15 कार्य दिवस (Working Days)",
        "validity": "1 Year (1 वित्तीय वर्ष)",
        "helpline": "03192-232143 / 1800-345-3197",
        "dept": "Revenue Department, Andaman & Nicobar Administration",
        "authOfficer": "Tehsildar / Assistant Commissioner",
        "code": "an"
    },
    "andhra-pradesh": {
        "nameEn": "Andhra Pradesh",
        "nameHi": "आंध्र प्रदेश",
        "portalName": "MeeSeva 2.0 / Grama Ward Sachivalayam",
        "portalUrl": "https://meeseva.ap.gov.in",
        "fee": "₹35",
        "timeline": "7 कार्य दिवस (Working Days)",
        "validity": "1 Year",
        "helpline": "1902 / 0863-2345678",
        "dept": "Revenue Department, Govt of Andhra Pradesh",
        "authOfficer": "Tahsildar",
        "code": "ap"
    },
    "arunachal-pradesh": {
        "nameEn": "Arunachal Pradesh",
        "nameHi": "अरुणाचल प्रदेश",
        "portalName": "ServicePlus Arunachal Portal",
        "portalUrl": "https://serviceonline.gov.in",
        "fee": "₹20",
        "timeline": "10 to 15 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0360-2212345",
        "dept": "Department of Land Management, Govt of Arunachal Pradesh",
        "authOfficer": "Extra Assistant Commissioner / Circle Officer",
        "code": "ar"
    },
    "assam": {
        "nameEn": "Assam",
        "nameHi": "असम",
        "portalName": "Sewa Setu Assam Portal (RTPS)",
        "portalUrl": "https://sewasetu.assam.gov.in",
        "fee": "₹30",
        "timeline": "5 to 10 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "1800-345-3574",
        "dept": "Revenue & Disaster Management Department, Govt of Assam",
        "authOfficer": "Circle Officer",
        "code": "as"
    },
    "bihar": {
        "nameEn": "Bihar",
        "nameHi": "बिहार",
        "portalName": "RTPS Bihar / ServicePlus Portal",
        "portalUrl": "https://serviceonline.bihar.gov.in",
        "fee": "₹0 (बिल्कुल निःशुल्क / Free)",
        "timeline": "10 कार्य दिवस (Working Days)",
        "validity": "1 Year (1 वर्ष)",
        "helpline": "1800-345-6284",
        "dept": "सामान्य प्रशासन विभाग, बिहार सरकार (General Administration Dept)",
        "authOfficer": "राजस्व अधिकारी (Revenue Officer / RO)",
        "code": "br"
    },
    "chandigarh": {
        "nameEn": "Chandigarh",
        "nameHi": "चंडीगढ़",
        "portalName": "e-District Chandigarh Portal",
        "portalUrl": "https://chdservices.gov.in",
        "fee": "₹30",
        "timeline": "7 to 10 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0172-2700018",
        "dept": "Estate Office / Revenue Department, Chandigarh Administration",
        "authOfficer": "Sub-Divisional Magistrate (SDM) / Tehsildar",
        "code": "ch"
    },
    "chhattisgarh": {
        "nameEn": "Chhattisgarh",
        "nameHi": "छत्तीसगढ़",
        "portalName": "e-District Chhattisgarh Portal (लोक सेवा केंद्र)",
        "portalUrl": "https://edistrict.cgstate.gov.in",
        "fee": "₹30",
        "timeline": "15 कार्य दिवस",
        "validity": "3 वर्ष (3 Years)",
        "helpline": "0771-2533350 / 1800-233-1111",
        "dept": "राजस्व एवं आपदा प्रबंधन विभाग, छत्तीसगढ़ शासन",
        "authOfficer": "तहसीलदार / नायब तहसीलदार",
        "code": "cg"
    },
    "dadra-nagar-haveli-daman-diu": {
        "nameEn": "Dadra & Nagar Haveli and Daman & Diu",
        "nameHi": "दादरा और नगर हवेली एवं दमन और दीव",
        "portalName": "e-District Daman & Diu Portal",
        "portalUrl": "https://daman.nic.in",
        "fee": "₹20",
        "timeline": "7 to 12 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0260-2230498",
        "dept": "Revenue Department, UT Administration of DNH & DD",
        "authOfficer": "Mamlatdar / Tehsildar",
        "code": "dn"
    },
    "delhi": {
        "nameEn": "Delhi (NCT)",
        "nameHi": "दिल्ली",
        "portalName": "e-District Delhi Portal",
        "portalUrl": "https://edistrict.delhigovt.nic.in",
        "fee": "₹0 (निःशुल्क) / ₹50 डोरस्टेप डिलीवरी",
        "timeline": "14 कार्य दिवस",
        "validity": "6 Months (6 महीने)",
        "helpline": "1076 (Doorstep Delivery) / 011-23935200",
        "dept": "Revenue Department, Govt of NCT of Delhi",
        "authOfficer": "Sub-Divisional Magistrate (SDM) / Executive Magistrate",
        "code": "dl"
    },
    "goa": {
        "nameEn": "Goa",
        "nameHi": "गोवा",
        "portalName": "Goa Online Services Portal",
        "portalUrl": "https://goaonline.gov.in",
        "fee": "₹50",
        "timeline": "7 कार्य दिवस",
        "validity": "3 Years",
        "helpline": "0832-2419700",
        "dept": "Department of Revenue, Govt of Goa",
        "authOfficer": "Mamlatdar / Talathi",
        "code": "ga"
    },
    "gujarat": {
        "nameEn": "Gujarat",
        "nameHi": "गुजरात",
        "portalName": "Digital Gujarat Portal",
        "portalUrl": "https://www.digitalgujarat.gov.in",
        "fee": "₹20",
        "timeline": "7 कार्य दिवस",
        "validity": "3 वर्ष (3 Years)",
        "helpline": "1800-233-5500",
        "dept": "Revenue Department, Govt of Gujarat",
        "authOfficer": "Mamlatdar / Talati",
        "code": "gj"
    },
    "haryana": {
        "nameEn": "Haryana",
        "nameHi": "हरियाणा",
        "portalName": "SARAL Haryana / Parivar Pehchan Patra (PPP)",
        "portalUrl": "https://saralharyana.gov.in",
        "fee": "₹0 to ₹30",
        "timeline": "7 कार्य दिवस",
        "validity": "1 Financial Year",
        "helpline": "1800-180-2128",
        "dept": "Citizen Resources Information Department (CRID) / Revenue Dept",
        "authOfficer": "Tehsildar / Verified by PPP Database",
        "code": "hr"
    },
    "himachal-pradesh": {
        "nameEn": "Himachal Pradesh",
        "nameHi": "हिमाचल प्रदेश",
        "portalName": "e-District Himachal Portal (eSewa)",
        "portalUrl": "https://edistrict.hp.gov.in",
        "fee": "₹17",
        "timeline": "7 to 10 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "1800-180-8076 / 1100",
        "dept": "Revenue Department, Govt of Himachal Pradesh",
        "authOfficer": "Tehsildar / Naib Tehsildar",
        "code": "hp"
    },
    "jammu-kashmir": {
        "nameEn": "Jammu & Kashmir",
        "nameHi": "जम्मू और कश्मीर",
        "portalName": "e-UNNAT Jammu & Kashmir Portal",
        "portalUrl": "https://serviceonline.gov.in",
        "fee": "₹25",
        "timeline": "15 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0194-2479231 / 0191-2546700",
        "dept": "Revenue Department, UT of Jammu & Kashmir",
        "authOfficer": "Tehsildar",
        "code": "jk"
    },
    "jharkhand": {
        "nameEn": "Jharkhand",
        "nameHi": "झारखंड",
        "portalName": "JharSewa / ServicePlus Jharkhand",
        "portalUrl": "https://jharsewa.jharkhand.gov.in",
        "fee": "₹0 (निःशुल्क) / ₹30 प्रज्ञा केंद्र",
        "timeline": "15 कार्य दिवस",
        "validity": "6 Months to 1 Year",
        "helpline": "1800-345-6531",
        "dept": "राजस्व, निबंधन एवं भूमि सुधार विभाग, झारखंड सरकार",
        "authOfficer": "अंचलाधिकारी (Circle Officer / CO)",
        "code": "jh"
    },
    "karnataka": {
        "nameEn": "Karnataka",
        "nameHi": "कर्नाटक",
        "portalName": "Seva Sindhu / Nadakacheri Portal",
        "portalUrl": "https://sevasindhu.karnataka.gov.in",
        "fee": "₹40",
        "timeline": "7 to 14 कार्य दिवस",
        "validity": "5 Years",
        "helpline": "080-22230060 / 1902",
        "dept": "Revenue Department, Govt of Karnataka",
        "authOfficer": "Tahsildar / Nadakacheri Deputy Tahsildar",
        "code": "ka"
    },
    "kerala": {
        "nameEn": "Kerala",
        "nameHi": "केरल",
        "portalName": "e-District Kerala Portal (Akshaya)",
        "portalUrl": "https://edistrict.kerala.gov.in",
        "fee": "₹25",
        "timeline": "5 to 7 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0471-2525444 / 155300",
        "dept": "Revenue Department, Govt of Kerala",
        "authOfficer": "Village Officer / Tahsildar",
        "code": "kl"
    },
    "ladakh": {
        "nameEn": "Ladakh",
        "nameHi": "लद्दाख",
        "portalName": "e-District Ladakh Portal",
        "portalUrl": "https://edistrict.ladakh.gov.in",
        "fee": "₹20",
        "timeline": "10 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "01982-255555",
        "dept": "Revenue Department, UT Administration of Ladakh",
        "authOfficer": "Tehsildar (Leh / Kargil)",
        "code": "la"
    },
    "lakshadweep": {
        "nameEn": "Lakshadweep",
        "nameHi": "लक्षद्वीप",
        "portalName": "e-District Lakshadweep Portal",
        "portalUrl": "https://lakshadweep.gov.in",
        "fee": "₹20",
        "timeline": "7 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "04896-262256",
        "dept": "Department of Revenue, UT of Lakshadweep",
        "authOfficer": "Deputy Collector / Sub-Divisional Officer",
        "code": "ld"
    },
    "madhya-pradesh": {
        "nameEn": "Madhya Pradesh",
        "nameHi": "मध्य प्रदेश",
        "portalName": "MP e-District (एमपी लोक सेवा गारंटी)",
        "portalUrl": "https://mpedistrict.gov.in",
        "fee": "₹0 (निःशुल्क) / ₹30 लोक सेवा केंद्र",
        "timeline": "3 कार्य दिवस (तत्काल) से 7 कार्य दिवस",
        "validity": "3 वर्ष (3 Years)",
        "helpline": "181 (CM Helpline)",
        "dept": "लोक सेवा प्रबंधन विभाग एवं राजस्व विभाग, म.प्र. शासन",
        "authOfficer": "तहसीलदार / नायब तहसीलदार",
        "code": "mp"
    },
    "maharashtra": {
        "nameEn": "Maharashtra",
        "nameHi": "महाराष्ट्र",
        "portalName": "Aaple Sarkar Portal (आपले सरकार)",
        "portalUrl": "https://aaplesarkar.mahaonline.gov.in",
        "fee": "₹33.60",
        "timeline": "15 कार्य दिवस",
        "validity": "1 Year या 3 Years (आवेदन अनुसार)",
        "helpline": "1800-120-8040",
        "dept": "महसूल विभाग, महाराष्ट्र शासन (Revenue Department)",
        "authOfficer": "नायब तहसीलदार / तहसीलदार",
        "code": "mh"
    },
    "manipur": {
        "nameEn": "Manipur",
        "nameHi": "मणिपुर",
        "portalName": "e-Services Manipur Portal",
        "portalUrl": "https://eservicesmanipur.gov.in",
        "fee": "₹30",
        "timeline": "10 कार्य दिवस",
        "validity": "6 Months to 1 Year",
        "helpline": "0385-2451234",
        "dept": "Department of Revenue, Govt of Manipur",
        "authOfficer": "Sub-Divisional Officer (SDO)",
        "code": "mn"
    },
    "meghalaya": {
        "nameEn": "Meghalaya",
        "nameHi": "मेघालय",
        "portalName": "e-District Meghalaya Portal",
        "portalUrl": "https://megedistrict.gov.in",
        "fee": "₹25",
        "timeline": "10 to 14 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0364-2225555",
        "dept": "Revenue & Disaster Management Dept, Govt of Meghalaya",
        "authOfficer": "Deputy Commissioner (DC) / SDO",
        "code": "ml"
    },
    "mizoram": {
        "nameEn": "Mizoram",
        "nameHi": "मिज़ोरम",
        "portalName": "e-District Mizoram Portal",
        "portalUrl": "https://edistrict.mizoram.gov.in",
        "fee": "₹20",
        "timeline": "7 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0389-2322234",
        "dept": "Land Revenue & Settlement Dept, Govt of Mizoram",
        "authOfficer": "Director / Sub-Divisional Officer",
        "code": "mz"
    },
    "nagaland": {
        "nameEn": "Nagaland",
        "nameHi": "नागालैंड",
        "portalName": "e-District Nagaland Portal",
        "portalUrl": "https://edistrict.nagaland.gov.in",
        "fee": "₹25",
        "timeline": "10 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0370-2270056",
        "dept": "Department of Personnel & Administrative Reforms, Govt of Nagaland",
        "authOfficer": "Deputy Commissioner (DC) / ADC",
        "code": "nl"
    },
    "odisha": {
        "nameEn": "Odisha",
        "nameHi": "ओडिशा",
        "portalName": "e-District Odisha (Odisha e-Governance)",
        "portalUrl": "https://edistrict.odisha.gov.in",
        "fee": "₹30",
        "timeline": "15 कार्य दिवस",
        "validity": "3 Years (3 वर्ष)",
        "helpline": "1800-121-5555",
        "dept": "Revenue & Disaster Management Dept, Govt of Odisha",
        "authOfficer": "Tahsildar / Additional Tahsildar",
        "code": "od"
    },
    "puducherry": {
        "nameEn": "Puducherry",
        "nameHi": "पुदुचेरी",
        "portalName": "e-District Puducherry Portal",
        "portalUrl": "https://edistrict.py.gov.in",
        "fee": "₹20",
        "timeline": "7 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "0413-2233344",
        "dept": "Department of Revenue & Disaster Management, UT of Puducherry",
        "authOfficer": "Tahsildar / Deputy Tahsildar",
        "code": "py"
    },
    "punjab": {
        "nameEn": "Punjab",
        "nameHi": "पंजाब",
        "portalName": "eSewa Punjab Portal / Connect Punjab",
        "portalUrl": "https://punjab.gov.in",
        "fee": "₹35 to ₹60",
        "timeline": "10 to 14 कार्य दिवस",
        "validity": "1 Financial Year",
        "helpline": "1100 (Connect Punjab)",
        "dept": "Department of Governance Reforms, Govt of Punjab",
        "authOfficer": "Tehsildar / Naib Tehsildar",
        "code": "pb"
    },
    "rajasthan": {
        "nameEn": "Rajasthan",
        "nameHi": "राजस्थान",
        "portalName": "e-Mitra Rajasthan / Jan Soochna Portal",
        "portalUrl": "https://emitra.rajasthan.gov.in",
        "fee": "₹40 to ₹50",
        "timeline": "7 कार्य दिवस",
        "validity": "6 Months to 1 Year",
        "helpline": "181 / 0141-2221424",
        "dept": "राजस्व विभाग, राजस्थान सरकार (Department of Revenue)",
        "authOfficer": "तहसीलदार / नायब तहसीलदार",
        "code": "rj"
    },
    "sikkim": {
        "nameEn": "Sikkim",
        "nameHi": "सिक्किम",
        "portalName": "Sikkim Services Portal (e-District)",
        "portalUrl": "https://services.sikkim.gov.in",
        "fee": "₹25",
        "timeline": "10 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "03592-202222",
        "dept": "Land Revenue & Disaster Management Dept, Govt of Sikkim",
        "authOfficer": "Sub-Divisional Magistrate (SDM)",
        "code": "sk"
    },
    "tamil-nadu": {
        "nameEn": "Tamil Nadu",
        "nameHi": "तमिलनाडु",
        "portalName": "TNeGA e-Sevai Portal",
        "portalUrl": "https://www.tnesevai.tn.gov.in",
        "fee": "₹60",
        "timeline": "7 to 15 कार्य दिवस",
        "validity": "1 Year (6 Months to 1 Year)",
        "helpline": "1800-425-1333 / 1100",
        "dept": "Revenue & Disaster Management Dept, Govt of Tamil Nadu",
        "authOfficer": "Zonal Deputy Tahsildar / Tahsildar",
        "code": "tn"
    },
    "telangana": {
        "nameEn": "Telangana",
        "nameHi": "तेलंगाना",
        "portalName": "MeeSeva Telangana Portal",
        "portalUrl": "https://meeseva.telangana.gov.in",
        "fee": "₹45",
        "timeline": "7 कार्य दिवस",
        "validity": "1 Year",
        "helpline": "1800-425-4440",
        "dept": "Revenue Department, Govt of Telangana",
        "authOfficer": "Tahsildar",
        "code": "tg"
    },
    "tripura": {
        "nameEn": "Tripura",
        "nameHi": "त्रिपुरा",
        "portalName": "e-District Tripura Portal",
        "portalUrl": "https://edistrict.tripura.gov.in",
        "fee": "₹20",
        "timeline": "7 to 10 कार्य दिवस",
        "validity": "6 Months to 1 Year",
        "helpline": "0381-2414013",
        "dept": "Revenue Department, Govt of Tripura",
        "authOfficer": "Deputy Collector & Magistrate (DCM)",
        "code": "tr"
    },
    "uttar-pradesh": {
        "nameEn": "Uttar Pradesh",
        "nameHi": "उत्तर प्रदेश",
        "portalName": "e-District UP (ई-डिस्ट्रिक्ट उत्तर प्रदेश)",
        "portalUrl": "https://edistrict.up.gov.in",
        "fee": "₹15 (Citizen Portal) / ₹30 (जन सेवा केंद्र / CSC)",
        "timeline": "7 से 15 कार्य दिवस (Working Days)",
        "validity": "3 वर्ष (3 Years from Date of Issue)",
        "helpline": "0522-2304706 / 1076 (CM Helpline)",
        "dept": "राजस्व विभाग, उत्तर प्रदेश शासन (Revenue Department UP)",
        "authOfficer": "तहसीलदार / नायब तहसीलदार",
        "code": "up"
    },
    "uttarakhand": {
        "nameEn": "Uttarakhand",
        "nameHi": "उत्तराखंड",
        "portalName": "eServices Uttarakhand (e-District)",
        "portalUrl": "https://eservices.uk.gov.in",
        "fee": "₹30",
        "timeline": "10 से 15 कार्य दिवस",
        "validity": "6 Months to 1 Year",
        "helpline": "1800-180-4025 / 1905 (CM Helpline)",
        "dept": "राजस्व विभाग, उत्तराखंड शासन",
        "authOfficer": "तहसीलदार / एसडीएम (SDM)",
        "code": "uk"
    },
    "west-bengal": {
        "nameEn": "West Bengal",
        "nameHi": "पश्चिम बंगाल",
        "portalName": "e-District West Bengal Portal",
        "portalUrl": "https://edistrict.wb.gov.in",
        "fee": "₹0 (निःशुल्क) / ₹20 BSK (Bangla Sahayata Kendra)",
        "timeline": "7 कार्य दिवस",
        "validity": "1 Financial Year (1 वित्तीय वर्ष)",
        "helpline": "1800-345-5555",
        "dept": "Personnel & Administrative Reforms Dept / Revenue Dept, Govt of West Bengal",
        "authOfficer": "Sub-Divisional Officer (SDO) / BDO",
        "code": "wb"
    }
}

print(f"Configured detailed metadata for {len(STATE_METADATA)} states/UTs.")
