# -*- coding: utf-8 -*-
BATCH_1 = {
    'uttar-pradesh-sir-voter-list': {
        'state_en': 'Uttar Pradesh',
        'state_hi': 'उत्तर प्रदेश',
        'slug': 'uttar-pradesh-sir-voter-list',
        'title': 'Uttar Pradesh Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Uttar Pradesh Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceouttarpradesh.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Uttar Pradesh',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी उत्तर प्रदेश',
        'total_ac': 403,
        'total_districts': 75,
        'districts': [
            {'name': 'Lucknow', 'ac': 'Lucknow West, Lucknow North, Lucknow East, Lucknow Central, Lucknow Cantt, Sarojini Nagar, Bakshi Kaa Talab, Mohanlalganj, Malihabad'},
            {'name': 'Kanpur Nagar', 'ac': 'Govind Nagar, Arya Nagar, Sisamau, Kanpur Cantt, Kidwai Nagar, Kalyanpur, Bithoor, Maharajpur, Ghatampur, Bilhaur'},
            {'name': 'Varanasi', 'ac': 'Varanasi North, Varanasi South, Varanasi Cantt, Rohaniya, Sevapuri, Shivpur, Ajgara, Pindra'},
            {'name': 'Prayagraj', 'ac': 'Allahabad West, Allahabad North, Allahabad South, Phaphamau, Soraon, Phulpur, Pratappur, Handia, Meja, Karachhana, Koraon, Bara'},
            {'name': 'Agra', 'ac': 'Agra Cantt, Agra South, Agra North, Agra Rural, Fatehabad, Bah, Kheragarh, Fatehpur Sikri, Etmadpur'},
            {'name': 'Meerut', 'ac': 'Meerut Cantt, Meerut City, Meerut South, Siwalkhas, Sardhana, Hastinapur, Kithore'},
            {'name': 'Ghaziabad', 'ac': 'Ghaziabad City, Sahibabad, Muradnagar, Loni, Modi Nagar'},
            {'name': 'Gautam Buddha Nagar (Noida)', 'ac': 'Noida, Dadri, Jewar'},
            {'name': 'Aligarh', 'ac': 'Aligarh, Koil, Barauli, Atrauli, Chharra, Khair, Iglas'},
            {'name': 'Bareilly', 'ac': 'Bareilly City, Bareilly Cantt, Bithari Chainpur, Nawabganj, Faridpur, Mirganj, Baheri, Aonla, Meerganj'},
            {'name': 'Moradabad', 'ac': 'Moradabad Nagar, Moradabad Rural, Kundarki, Bilari, Kanth, Thakurdwara'},
            {'name': 'Gorakhpur', 'ac': 'Gorakhpur Urban, Gorakhpur Rural, Pipraich, Campierganj, Sahjanwa, Khajani, Chauri-Chaura, Bansgaon, Chillupar'},
            {'name': 'Ayodhya (Faizabad)', 'ac': 'Ayodhya City, Rudauli, Bikapur, Milkipur, Gosainganj'},
            {'name': 'Jhansi', 'ac': 'Jhansi Nagar, Babina, Mauranipur, Garautha'},
            {'name': 'Mathura', 'ac': 'Mathura City, Vrindavan, Goverdhan, Chhata, Mant, Baldeo'},
            {'name': 'Muzaffarnagar', 'ac': 'Muzaffarnagar City, Budhana, Charthawal, Purqazi, Khatoli, Meerapur'},
            {'name': 'Saharanpur', 'ac': 'Saharanpur Nagar, Saharanpur, Deoband, Behat, Nakur, Gangoh, Rampur Maniharan'},
            {'name': 'Firozabad', 'ac': 'Firozabad, Tundla, Jasrana, Shikohabad, Sirsaganj'},
            {'name': 'Mainpuri', 'ac': 'Mainpuri, Karhal, Kishni, Bhongaon'},
            {'name': 'Etawah', 'ac': 'Etawah, Jaswantnagar, Bharthana'},
            {'name': 'Bulandshahr', 'ac': 'Bulandshahr, Syana, Anupshahr, Debai, Shikarpur, Khurja, Sikandrabad'},
            {'name': 'Budaun', 'ac': 'Budaun, Bisauli, Sahaswan, Bilsi, Shekhupur, Dataganj'},
            {'name': 'Shahjahanpur', 'ac': 'Shahjahanpur City, Dadraul, Katra, Jalalabad, Tilhar, Powayan'},
            {'name': 'Pilibhit', 'ac': 'Pilibhit, Barkhera, Puranpur, Bisalpur'},
            {'name': 'Lakhimpur Kheri', 'ac': 'Kheri, Palia, Nighasan, Gola Gokrannath, Srinagar, Dhaurahra, Mohammadi, Kastaa'},
            {'name': 'Sitapur', 'ac': 'Sitapur, Hargaon, Laharpur, Biswan, Sevata, Mahmoodabad, Sidhauli, Misrikh'},
            {'name': 'Hardoi', 'ac': 'Hardoi, Gopamau, Sandi, Bilgram-Mallanwan, Balamau, Sandila, Shahabad, Sawayajpur'},
            {'name': 'Unnao', 'ac': 'Unnao, Bangarmau, Safipur, Mohan, Purwa, Bhagwant Nagar'},
            {'name': 'Rae Bareli', 'ac': 'Rae Bareli, Bachhrawan, Harchandpur, Sareni, Salon, Unchahar'},
            {'name': 'Amethi', 'ac': 'Amethi, Tiloi, Jagdishpur, Gauriganj'},
            {'name': 'Sultanpur', 'ac': 'Sultanpur, Isauli, Sultanpur Sadar, Lambhua, Kadipur'},
            {'name': 'Barabanki', 'ac': 'Barabanki, Kursi, Ram Nagar, Zaidpur, Dariyabad, Haidergarh'},
            {'name': 'Gonda', 'ac': 'Gonda, Gaura, Colonelganj, Tarabganj, Mankapur, Mehnaun, Katra Bazar'},
            {'name': 'Bahraich', 'ac': 'Bahraich, Mahasi, Payagpur, Kaiserganj, Matera, Balha, Nanpara'},
            {'name': 'Shravasti', 'ac': 'Bhinga, Shravasti'},
            {'name': 'Balrampur', 'ac': 'Balrampur, Tulsipur, Gainsari, Utraula'},
            {'name': 'Basti', 'ac': 'Basti Sadar, Harraiya, Kaptanganj, Rudhauli, Mahadewa'},
            {'name': 'Siddharthnagar', 'ac': 'Naugarh, Shohratgarh, Kapilvastu, Bansi, Itwa, Domariyaganj'},
            {'name': 'Sant Kabir Nagar', 'ac': 'Khalilabad, Menhdawal, Dhanghata'},
            {'name': 'Maharajganj', 'ac': 'Maharajganj, Pharenda, Nautanwa, Siswa, Paniyara'},
            {'name': 'Kushinagar', 'ac': 'Kushinagar, Padrauna, Khadda, Ramkola, Hata, Fazilnagar, Tamkuhi Raj'},
            {'name': 'Deoria', 'ac': 'Deoria, Rudrapur, Pathardeva, Rampur Karkhana, Bhatpar Rani, Salempur, Barhaj'},
            {'name': 'Azamgarh', 'ac': 'Azamgarh, Gopalpur, Sagri, Mubarakpur, Mehnagar, Nizamabad, Phoolpur Pawai, Didarganj, Lalganj, Atraulia'},
            {'name': 'Mau', 'ac': 'Mau, Madhuban, Ghosi, Muhammadabad-Gohna'},
            {'name': 'Ballia', 'ac': 'Ballia Nagar, Rasara, Bansdih, Bairia, Belthara Road, Sikanderpur, Phephana'},
            {'name': 'Jaunpur', 'ac': 'Jaunpur, Malhani, Mungra Badshahpur, Machhlishahr, Mariyahu, Zafarabad, Kerakat, Shahganj, Badlapur'},
            {'name': 'Ghazipur', 'ac': 'Ghazipur, Jangipur, Zahoorabad, Mohammadabad, Zamania, Saidpur, Jakhanian'},
            {'name': 'Chandauli', 'ac': 'Mughalsarai, Sakaldiha, Saiyadraja, Chakia'},
            {'name': 'Mirzapur', 'ac': 'Mirzapur, Chhanbey, Majhawan, Chunar, Marihan'},
            {'name': 'Sonbhadra', 'ac': 'Robertsganj, Obra, Duddhi, Ghorawal'},
            {'name': 'Bhadohi', 'ac': 'Bhadohi, Gyanpur, Aurai'},
            {'name': 'Banda', 'ac': 'Banda, Naraini, Baberu, Tindwari'},
            {'name': 'Chitrakoot', 'ac': 'Chitrakoot, Manikpur'},
            {'name': 'Hamirpur', 'ac': 'Hamirpur, Rath'},
            {'name': 'Mahoba', 'ac': 'Mahoba, Charkhari'},
            {'name': 'Jalaun', 'ac': 'Orai, Kalpi, Madhogarh'},
            {'name': 'Lalitpur', 'ac': 'Lalitpur, Mehroni'},
            {'name': 'Farrukhabad', 'ac': 'Farrukhabad, Kaimganj, Amritpur, Bhojpur'},
            {'name': 'Kannauj', 'ac': 'Kannauj, Chhibramau, Tirwa'},
            {'name': 'Auraiya', 'ac': 'Auraiya, Bidhuna, Dibiyapur'},
            {'name': 'Etah', 'ac': 'Etah, Aliganj, Marhara, Jalesar'},
            {'name': 'Kasganj', 'ac': 'Kasganj, Amanpur, Patiyali'},
            {'name': 'Hathras', 'ac': 'Hathras, Sadabad, Sikandra Rao'},
            {'name': 'Hapur', 'ac': 'Hapur, Garhmukteshwar, Dholana'},
            {'name': 'Baghpat', 'ac': 'Baghpat, Baraut, Chhaprauli'},
            {'name': 'Shamli', 'ac': 'Shamli, Kairana, Thana Bhawan'},
            {'name': 'Sambhal', 'ac': 'Sambhal, Asmoli, Chandausi, Gunnaur'},
            {'name': 'Amroha', 'ac': 'Amroha, Hasanpur, Dhanaura, Naugawan Sadat'},
            {'name': 'Bijnor', 'ac': 'Bijnor, Chandpur, Noorpur, Dhampur, Nagina, Barhapur, Nehtaur, Najibabad'},
            {'name': 'Rampur', 'ac': 'Rampur, Suar, Chamraua, Bilaspur, Milak'},
            {'name': 'Fatehpur', 'ac': 'Fatehpur, Bindki, Jahanabad, Husainganj, Khaga, Ayah Shah'},
            {'name': 'Kaushambi', 'ac': 'Sirathu, Manjhanpur, Chail'},
            {'name': 'Pratapgarh', 'ac': 'Pratapgarh, Patti, Raniganj, Kunda, Babaganj, Vishwanathganj, Rampur Khas'}
        ]
    },
    'bihar-sir-voter-list': {
        'state_en': 'Bihar',
        'state_hi': 'बिहार',
        'slug': 'bihar-sir-voter-list',
        'title': 'Bihar Sir Voter List 2026: Online Apply, Eligibility & Documents',
        'desc': 'Bihar Sir Voter List 2026 online apply process, eligibility criteria, required documents, fee details aur direct official portal link.',
        'ceo_url': 'https://ceobihar.nic.in',
        'ceo_name': 'Chief Electoral Officer (CEO) Bihar',
        'ceo_name_hi': 'मुख्य निर्वाचन अधिकारी बिहार',
        'total_ac': 243,
        'total_districts': 38,
        'districts': [
            {'name': 'Patna', 'ac': 'Kumhrar, Bankipur, Digha, Patna Sahib, Danapur, Maner, Phulwari, Fatuha, Bakhtiarpur, Mokama, Barh, Masaurhi, Bikram, Paliganj'},
            {'name': 'Gaya', 'ac': 'Gaya Town, Belaganj, Atri, Wazirganj, Bodh Gaya, Tikari, Sherghati, Imamganj, Barachatti, Gurua'},
            {'name': 'Muzaffarpur', 'ac': 'Muzaffarpur, Kanti, Baruraj, Paroo, Sahebganj, Bochahan, Sakra, Kurhani, Aurai, Gaighat, Minapur'},
            {'name': 'Bhagalpur', 'ac': 'Bhagalpur, Kahalgaon, Sultanganj, Nathnagar, Bihpur, Gopalpur, Pirpainti'},
            {'name': 'Darbhanga', 'ac': 'Darbhanga, Darbhanga Rural, Benipur, Alinagar, Hayaghat, Bahadurpur, Keoti, Jale, Kusheshwar Asthan, Gaura Bauram'},
            {'name': 'Purnia', 'ac': 'Purnia, Kasba, Banmankhi, Rupauli, Dhamdaha, Amour, Baisi'},
            {'name': 'Saran (Chhapra)', 'ac': 'Chhapra, Marhaura, Garkha, Amnour, Parsa, Sonepur, Taraiya, Ekma, Manjhi, Baniapur'},
            {'name': 'Samastipur', 'ac': 'Samastipur, Kalyanpur, Warisnagar, Ujiarpur, Morwa, Sarairanjan, Mohiuddinnagar, Bibhutipur, Rosera, Hasanpur'},
            {'name': 'Begusarai', 'ac': 'Begusarai, Bachhwara, Teghra, Matihani, Sahebpur Kamal, Bakhri, Cheria Bariarpur'},
            {'name': 'Nalanda', 'ac': 'Biharsharif, Nalanda, Rajgir, Islampur, Hilsa, Asthawan, Harnaut'},
            {'name': 'Vaishali (Hajipur)', 'ac': 'Hajipur, Lalganj, Vaishali, Mahua, Raja Pakar, Raghopur, Patepur, Mahnar'},
            {'name': 'Siwan', 'ac': 'Siwan, Ziradei, Darauli, Raghunathpur, Daraundha, Barharia, Goriakothi, Maharajganj'},
            {'name': 'Gopalganj', 'ac': 'Gopalganj, Baikunthpur, Barauli, Kuchaikote, Bhore, Hathua'},
            {'name': 'East Champaran (Motihari)', 'ac': 'Motihari, Raxaul, Sugauli, Narkatiya, Harsidhi, Govindganj, Kesaria, Kalyanpur, Pipra, Madhuban, Chiraia, Dhaka'},
            {'name': 'West Champaran (Bettiah)', 'ac': 'Bettiah, Valmiki Nagar, Ramnagar, Narkatiaganj, Bagaha, Lauriya, Nautan, Chanpatia, Sikta'},
            {'name': 'Sitamarhi', 'ac': 'Sitamarhi, Riga, Bathnaha, Parihar, Sursand, Bajpatti, Belsand, Runnisaidpur'},
            {'name': 'Madhubani', 'ac': 'Madhubani, Benipatti, Khajauli, Babubarhi, Bisfi, Harlakhi, Rajnagar, Jhanjharpur, Phulparas, Laukaha'},
            {'name': 'Katihar', 'ac': 'Katihar, Kadwa, Balrampur, Pranpur, Manihari, Barari, Korha'},
            {'name': 'Rohtas (Sasaram)', 'ac': 'Sasaram, Chenari, Kargahar, Dinara, Nokha, Dehri, Karakat'},
            {'name': 'Bhojpur (Ara)', 'ac': 'Ara, Sandesh, Barhara, Agiaon, Tarari, Jagdishpur, Shahpur'},
            {'name': 'Buxar', 'ac': 'Buxar, Dumraon, Rajpur, Brahmpur'},
            {'name': 'Kaimur (Bhabua)', 'ac': 'Bhabua, Mohania, Chainpur, Ramgarh'},
            {'name': 'Nawada', 'ac': 'Nawada, Rajauli, Hisua, Warsiliganj, Gobindpur'},
            {'name': 'Aurangabad', 'ac': 'Aurangabad, Rafiganj, Gurua, Obra, Goh, Kutumba, Nabinagar'},
            {'name': 'Jehanabad', 'ac': 'Jehanabad, Makhdumpur, Ghosi'},
            {'name': 'Arwal', 'ac': 'Arwal, Kurtha'},
            {'name': 'Saharsa', 'ac': 'Saharsa, Sonbarsha, Simri Bakhtiarpur, Mahishi'},
            {'name': 'Supaul', 'ac': 'Supaul, Nirmali, Pipra, Triveniganj, Chhatapur'},
            {'name': 'Madhepura', 'ac': 'Madhepura, Singheshwar, Bihariganj, Alamnagar'},
            {'name': 'Kishanganj', 'ac': 'Kishanganj, Bahadurganj, Thakurganj, Kochadhaman'},
            {'name': 'Araria', 'ac': 'Araria, Forbesganj, Raniganj, Jokihat, Sikti, Narpatganj'},
            {'name': 'Munger', 'ac': 'Munger, Jamalpur, Tarapur'},
            {'name': 'Jamui', 'ac': 'Jamui, Sikandra, Jhajha, Chakai'},
            {'name': 'Lakhisarai', 'ac': 'Lakhisarai, Suryagarha'},
            {'name': 'Sheikhpura', 'ac': 'Sheikhpura, Barbigha'},
            {'name': 'Khagaria', 'ac': 'Khagaria, Beldaur, Parbatta, Alauli'},
            {'name': 'Banka', 'ac': 'Banka, Amarpur, Dhoraiya, Katoria, Belhar'},
            {'name': 'Sheohar', 'ac': 'Sheohar'}
        ]
    }
}
print('Batch 1 data ready (UP, Bihar)...')
